/* Label Lens 配料镜 (HalalCheck) knowledge base — part 5: NON-FOOD items
 * (wet wipes, tissues, soap, shampoo, toothpaste, mouthwash, skincare, cosmetics, detergents, sanitisers, perfume).
 * Owner rule for non-food: ALCOHOL IS ACCEPTABLE; the item must be FREE OF ANIMAL PRODUCTS AND BY-PRODUCTS.
 *
 * detect:   [zh, en] words that mark a label as non-food. Entries before ['--weak--', ''] are STRONG (one hit is enough);
 *           entries after it are WEAK (two needed, and only when no food marker such as 配料表/营养成分 is present).
 * entries:  [zh, status, en, pinyin, category, note]   — longest match wins; these override the food dictionary.
 *   status: 'haram'   pig- or carrion-derived, or explicitly pork
 *           'animal'  animal-derived, not pig (includes human-derived and species-unstated animal material)
 *           'unsure'  animal OR plant/synthetic, source not stated on the label (the user decides)
 *                     (the task brief called this 'unknown'; analyzer.js and app.js use 'unsure', so 'unsure' is used here)
 *           'alcohol' an alcohol or glycol: informational, acceptable in non-food items
 *           'ok'      plant / mineral / synthetic lookalike, listed so it is NOT confused with an animal term
 *   category: pig, bovine, ovine, insect, marine, bird, dairy, egg, bee, snail, human, mixed, alcohol, plant, synthetic, mineral
 *             (mixed = other or unstated animal species: horse, donkey, deer, snake, bear, mink, unstated tallow/gelatin, etc.)
 * products: [names separated by |, level, en, typical ingredients, what decides]; level: clean | caution | animal | haram
 */
var HALAL_NONFOOD = {
  version: '2026-10-08',
  detect: [
    // ---------- strong: one hit marks the label as non-food
    ['化妆品', 'cosmetics'], ['卫妆准字', 'cosmetic approval no. (old)'], ['国妆特字', 'special-use cosmetic registration'], ['国妆备进字', 'imported cosmetic filing'],
    ['妆字号', 'cosmetic licence no.'], ['妆网备', 'cosmetic online filing no.'], ['妆备字', 'cosmetic filing no.'], ['消字号', 'disinfection product licence'],
    ['卫消证字', 'disinfection product licence'], ['械字号', 'medical device licence'], ['械注准', 'medical device registration'], ['械备', 'medical device filing'], ['国妆特进字', 'imported special-use cosmetic'], ['GB 15979', 'GB 15979 disposable hygiene products'],
    ['GB15979', 'GB 15979 disposable hygiene products'], ['GB/T 27728', 'GB/T 27728 wet wipes'], ['GB/T27728', 'GB/T 27728 wet wipes'], ['GB/T 20808', 'GB/T 20808 facial tissue'],
    ['GB/T 8372', 'GB/T 8372 toothpaste'], ['GB/T 29679', 'GB/T 29679 shampoo'], ['全成分', 'full ingredient list (cosmetics)'], ['适用肤质', 'suitable skin type'],
    ['用于完整皮肤', 'for intact skin'], ['外用', 'for external use'], ['限期使用日期', 'use-by date (cosmetics)'], ['使用期限', 'period of use'],
    ['INCI', 'INCI names'], ['面巾纸', 'facial tissue'], ['卫生纸', 'toilet paper'], ['抽纸', 'tissue box'],
    ['卫生巾', 'sanitary pads'], ['护垫', 'panty liners'], ['尿裤', 'diapers'], ['纸尿裤', 'disposable diapers'], ['化妆棉', 'cotton pads'], ['棉签', 'cotton swabs'],
    ['洗衣液', 'laundry liquid'], ['洗衣粉', 'washing powder'], ['洗衣凝珠', 'laundry pods'], ['柔顺剂', 'fabric softener'], ['洗洁精', 'dishwashing liquid'],
    ['洗涤剂', 'detergent'], ['清洁剂', 'cleaner'], ['消毒液', 'disinfectant'], ['酒精棉片', 'alcohol pads'],
    ['免洗洗手液', 'leave-on hand sanitiser'], ['洗手液', 'hand wash'], ['护手霜', 'hand cream'], ['面膜', 'face mask'], ['爽肤水', 'toner'], ['化妆水', 'toner / lotion'],
    ['防晒', 'sunscreen'], ['防晒霜', 'sunscreen cream'], ['隔离霜', 'primer / makeup base'], ['口红', 'lipstick'], ['唇膏', 'lip balm / lipstick'], ['唇釉', 'lip glaze'],
    ['牙膏', 'toothpaste'], ['牙刷', 'toothbrush'], ['漱口水', 'mouthwash'], ['沐浴露', 'shower gel'], ['沐浴乳', 'body wash'], ['洗发水', 'shampoo'], ['洗发露', 'shampoo'],
    ['护发素', 'conditioner'], ['发膜', 'hair mask'], ['香皂', 'toilet soap'], ['肥皂', 'soap'], ['洗面奶', 'facial cleanser'], ['洁面', 'facial cleanser'],
    ['卸妆', 'makeup remover'], ['眼霜', 'eye cream'], ['面霜', 'face cream'], ['身体乳', 'body lotion'], ['润肤霜', 'moisturising cream'], ['彩妆', 'colour cosmetics'],
    ['洗护', 'wash and care'], ['剃须', 'shaving'], ['指甲油', 'nail polish'], ['睫毛膏', 'mascara'], ['粉底液', 'liquid foundation'], ['粉底霜', 'foundation cream'],
    ['气垫', 'cushion compact'], ['遮瑕', 'concealer'], ['腮红', 'blush'], ['眼影', 'eyeshadow'], ['眉笔', 'eyebrow pencil'], ['眼线', 'eyeliner'], ['发胶', 'hair spray'],
    ['定型喷雾', 'styling spray'], ['染发', 'hair dye'], ['驱蚊', 'mosquito repellent'], ['驱蚊液', 'mosquito repellent liquid'], ['花露水', 'florida water'],
    ['BB霜', 'BB cream'],
    ['限用日期', 'use-by date (cosmetics/hygiene)'], ['生活用纸', 'household paper products'], ['皮肤刺激试验', 'skin irritation test'], ['用于皮肤', 'for use on skin'], ['清洁皮肤', 'cleans the skin'], ['中国药典纯化水', 'pharmacopoeia purified water'],
    ['--weak--', ''],
    ['不添加酒精', 'no alcohol added'], ['不含酒精', 'alcohol-free'], ['皮肤', 'skin'], ['温和不刺激', 'mild, non-irritating'],
    // ---------- weak: these also appear on food packs (desiccant sachets, nutrition panels, drinks, wipes packed with food,
    //            酸辣粉底料 / 米粉饼 contain 粉底 / 粉饼, health-food claims such as 养颜润肤)
    ['湿巾', 'wet wipes'], ['湿纸巾', 'wet tissue'], ['消毒湿巾', 'disinfecting wipes'], ['粉底', 'foundation'], ['粉饼', 'pressed powder'], ['散粉', 'loose powder'],
    ['香氛', 'fragrance'], ['润肤', 'moisturising'], ['护肤', 'skincare'],
    ['成分', 'ingredients / composition'], ['使用方法', 'directions for use'], ['使用范围', 'scope of use'], ['请勿食用', 'do not eat'], ['乳液', 'lotion / emulsion'],
    ['精华液', 'serum'], ['精华', 'essence'], ['香水', 'perfume'], ['纸巾', 'tissue'], ['非织造布', 'nonwoven fabric'], ['无纺布', 'nonwoven fabric'], ['皮肤', 'skin'],
    ['抑菌', 'bacteriostatic'], ['抗菌', 'antibacterial'], ['去污', 'stain removal'], ['避免接触眼睛', 'avoid contact with eyes'], ['儿童不能触及', 'keep out of reach of children']
  ],
  entries: [
    // ================= PIG (haram)
    ['猪', 'haram', 'pig', 'zhū', 'pig', 'Any pig-named material is pig-derived.'],
    ['猪油', 'haram', 'lard', 'zhū yóu', 'pig', 'Pig fat, used in some soaps, balms and handmade cosmetics.'],
    ['猪脂', 'haram', 'pork fat', 'zhū zhī', 'pig', 'Pig fat.'],
    ['猪源', 'haram', 'porcine-derived', 'zhū yuán', 'pig', 'Stated as pig origin.'],
    ['猪皮', 'haram', 'pig skin', 'zhū pí', 'pig', 'Pig skin, a source of collagen and gelatin.'],
    ['猪胶原', 'haram', 'porcine collagen', 'zhū jiāo yuán', 'pig', 'Collagen from pig skin or bone.'],
    ['猪胶原蛋白', 'haram', 'porcine collagen', 'zhū jiāo yuán dàn bái', 'pig', 'Collagen from pig skin or bone.'],
    ['猪明胶', 'haram', 'pork gelatin', 'zhū míng jiāo', 'pig', 'Gelatin from pig skin or bone.'],
    ['猪胎盘', 'haram', 'porcine placenta', 'zhū tāi pán', 'pig', 'Pig placenta extract, sold in anti-ageing creams and supplements.'],
    ['猪鬃', 'haram', 'hog bristle', 'zhū zōng', 'pig', 'Pig hair used in toothbrushes, hairbrushes and makeup brushes.'],
    ['猪毛', 'haram', 'pig hair', 'zhū máo', 'pig', 'Pig hair used in brushes.'],
    ['猪胆汁', 'haram', 'pig bile', 'zhū dǎn zhī', 'pig', 'Pig bile, used in some traditional preparations.'],
    ['猪胆粉', 'haram', 'pig bile powder', 'zhū dǎn fěn', 'pig', 'Dried pig bile.'],
    ['猪去氧胆酸', 'haram', 'hyodeoxycholic acid', 'zhū qù yǎng dǎn suān', 'pig', 'Bile acid from pig bile; an ingredient of artificial bezoar.'],
    ['猪骨', 'haram', 'pig bone', 'zhū gǔ', 'pig', 'Pig bone.'],
    ['人工牛黄', 'haram', 'artificial bezoar', 'rén gōng niú huáng', 'pig', 'Chinese Pharmacopoeia formula includes pig hyodeoxycholic acid and ox bile powder.'],
    ['Lard', 'haram', 'lard', '', 'pig', 'Pig fat.'],
    ['Porcine', 'haram', 'porcine (pig)', '', 'pig', 'Pig origin.'],
    ['Pork', 'haram', 'pork', '', 'pig', 'Pig.'],

    // ================= BOVINE
    ['牛脂', 'animal', 'beef tallow', 'niú zhī', 'bovine', 'Cattle fat; soap base and fatty-acid source.'],
    ['牛油', 'animal', 'beef tallow', 'niú yóu', 'bovine', 'Cattle fat. Not 牛油果 (avocado) or 牛油果树 (shea).'],
    ['牛脂酸钠', 'animal', 'sodium tallowate', 'niú zhī suān nà', 'bovine', 'Soap made from tallow.'],
    ['牛脂酸钾', 'animal', 'potassium tallowate', 'niú zhī suān jiǎ', 'bovine', 'Soft soap made from tallow.'],
    ['牛脂基', 'animal', 'tallow-derived (tallowalkyl)', 'niú zhī jī', 'bovine', 'Tallow-derived surfactant or softener quat, e.g. in fabric softener.'],
    ['牛胶原蛋白', 'animal', 'bovine collagen', 'niú jiāo yuán dàn bái', 'bovine', 'Collagen from cattle hide or bone.'],
    ['牛胶原', 'animal', 'bovine collagen', 'niú jiāo yuán', 'bovine', 'Collagen from cattle hide or bone.'],
    ['牛骨', 'animal', 'cattle bone', 'niú gǔ', 'bovine', 'Cattle bone.'],
    ['牛黄', 'animal', 'bezoar (ox gallstone)', 'niú huáng', 'bovine', 'Cattle gallstone; if 人工牛黄 it also contains pig bile acid.'],
    ['牛胆汁', 'animal', 'ox bile', 'niú dǎn zhī', 'bovine', 'Cattle bile.'],
    ['Tallow', 'animal', 'tallow', '', 'bovine', 'Rendered animal fat, usually cattle.'],
    ['Sodium Tallowate', 'animal', 'sodium tallowate', '', 'bovine', 'Soap made from tallow.'],

    // ================= DAIRY
    ['牛奶', 'animal', 'cow milk', 'niú nǎi', 'dairy', 'Milk ingredient.'],
    ['牛乳', 'animal', 'cow milk', 'niú rǔ', 'dairy', 'Milk ingredient.'],
    ['牛奶蛋白', 'animal', 'milk protein', 'niú nǎi dàn bái', 'dairy', 'Milk protein.'],
    ['牛初乳', 'animal', 'bovine colostrum', 'niú chū rǔ', 'dairy', 'Cow colostrum.'],
    ['乳蛋白', 'animal', 'milk protein', 'rǔ dàn bái', 'dairy', 'Milk protein.'],
    ['酪蛋白', 'animal', 'casein', 'lào dàn bái', 'dairy', 'Milk protein.'],
    ['乳清', 'animal', 'whey', 'rǔ qīng', 'dairy', 'Milk by-product.'],
    ['乳清蛋白', 'animal', 'whey protein', 'rǔ qīng dàn bái', 'dairy', 'Milk protein.'],
    ['乳铁蛋白', 'animal', 'lactoferrin', 'rǔ tiě dàn bái', 'dairy', 'Protein isolated from milk.'],
    ['乳糖', 'animal', 'lactose', 'rǔ táng', 'dairy', 'Milk sugar.'],
    ['乳脂', 'animal', 'milk fat', 'rǔ zhī', 'dairy', 'Milk fat.'],
    ['黄油', 'animal', 'butter', 'huáng yóu', 'dairy', 'Milk fat. Not 乳木果油 (shea butter).'],
    ['奶粉', 'animal', 'milk powder', 'nǎi fěn', 'dairy', 'Dried milk.'],
    ['酸奶', 'animal', 'yoghurt', 'suān nǎi', 'dairy', 'Fermented milk.'],
    ['羊奶', 'animal', 'goat milk', 'yáng nǎi', 'dairy', 'Goat or sheep milk, popular in soaps and lotions.'],
    ['羊乳', 'animal', 'goat milk', 'yáng rǔ', 'dairy', 'Goat or sheep milk.'],
    ['驴奶', 'animal', 'donkey milk', 'lǘ nǎi', 'dairy', 'Donkey milk, used in soaps and creams.'],
    ['驴乳', 'animal', 'donkey milk', 'lǘ rǔ', 'dairy', 'Donkey milk.'],
    ['Casein', 'animal', 'casein', '', 'dairy', 'Milk protein.'],

    // ================= OVINE
    ['羊毛脂', 'animal', 'lanolin', 'yáng máo zhī', 'ovine', 'Wool grease from sheep fleece.'],
    ['羊毛脂醇', 'animal', 'lanolin alcohol', 'yáng máo zhī chún', 'ovine', 'Fraction of wool grease.'],
    ['羊毛脂酸', 'animal', 'lanolin acid', 'yáng máo zhī suān', 'ovine', 'Fraction of wool grease.'],
    ['羊毛', 'animal', 'wool', 'yáng máo', 'ovine', 'Sheep wool.'],
    ['羊绒', 'animal', 'cashmere', 'yáng róng', 'ovine', 'Goat down fibre.'],
    ['绵羊油', 'animal', 'sheep oil (lanolin cream)', 'mián yáng yóu', 'ovine', 'Hand creams sold as sheep oil are lanolin-based.'],
    ['羊油', 'animal', 'mutton fat', 'yáng yóu', 'ovine', 'Sheep or goat fat.'],
    ['羊脂', 'animal', 'mutton tallow', 'yáng zhī', 'ovine', 'Sheep or goat fat. Not 羊脂玉 (jade).'],
    ['羊胎素', 'animal', 'sheep placenta extract', 'yáng tāi sù', 'ovine', 'Sheep placenta or fetal tissue extract.'],
    ['羊胎盘', 'animal', 'sheep placenta', 'yáng tāi pán', 'ovine', 'Sheep placenta.'],
    ['Lanolin', 'animal', 'lanolin', '', 'ovine', 'Wool grease from sheep.'],

    // ================= OTHER / UNSTATED MAMMALS (mixed)
    ['马油', 'animal', 'horse oil', 'mǎ yóu', 'mixed', 'Horse fat, popular in Chinese and Japanese creams.'],
    ['马脂', 'animal', 'horse fat', 'mǎ zhī', 'mixed', 'Horse fat.'],
    ['马毛', 'animal', 'horse hair', 'mǎ máo', 'mixed', 'Horse hair, used in brushes.'],
    ['驴油', 'animal', 'donkey fat', 'lǘ yóu', 'mixed', 'Donkey fat.'],
    ['阿胶', 'animal', 'donkey-hide gelatin (ejiao)', 'ē jiāo', 'mixed', 'Gelatin from donkey hide; adulteration with other hides has been reported.'],
    ['鹿茸', 'animal', 'deer antler velvet', 'lù róng', 'mixed', 'Deer antler.'],
    ['鹿角', 'animal', 'deer antler', 'lù jiǎo', 'mixed', 'Deer antler. Not 鹿角菜 (seaweed).'],
    ['鹿胎', 'animal', 'deer fetus / placenta', 'lù tāi', 'mixed', 'Deer fetal tissue.'],
    ['麝香', 'animal', 'musk', 'shè xiāng', 'mixed', 'Natural musk is from the musk deer; perfumes usually use synthetic musk, labelled 合成麝香 or 人工麝香.'],
    ['灵猫香', 'animal', 'civet', 'líng māo xiāng', 'mixed', 'Secretion of the civet cat.'],
    ['海狸香', 'animal', 'castoreum', 'hǎi lí xiāng', 'mixed', 'Beaver gland secretion.'],
    ['貂油', 'animal', 'mink oil', 'diāo yóu', 'mixed', 'Mink fat.'],
    ['貂毛', 'animal', 'mink hair', 'diāo máo', 'mixed', 'Mink hair, used in lash extensions and brushes.'],
    ['獾毛', 'animal', 'badger hair', 'huān máo', 'mixed', 'Badger hair, used in shaving brushes.'],
    ['熊胆', 'animal', 'bear bile', 'xióng dǎn', 'mixed', 'Bear bile.'],
    ['蛇油', 'animal', 'snake oil', 'shé yóu', 'mixed', 'Snake fat, used in some hand creams.'],
    ['蛇胆', 'animal', 'snake bile', 'shé dǎn', 'mixed', 'Snake bile, used in some toilet waters and soaps.'],
    ['蛇蜕', 'animal', 'snake slough', 'shé tuì', 'mixed', 'Shed snake skin.'],
    ['鳄鱼油', 'animal', 'crocodile oil', 'è yú yóu', 'mixed', 'Crocodile fat.'],
    ['胆汁', 'animal', 'bile', 'dǎn zhī', 'mixed', 'Animal bile; species unstated.'],
    ['动物油脂', 'animal', 'animal fat', 'dòng wù yóu zhī', 'mixed', 'Species unstated; may be lard.'],
    ['动物油', 'animal', 'animal oil', 'dòng wù yóu', 'mixed', 'Species unstated; may be lard.'],
    ['动物脂肪', 'animal', 'animal fat', 'dòng wù zhī fáng', 'mixed', 'Species unstated; may be lard.'],
    ['氢化动物油', 'animal', 'hydrogenated animal oil', 'qīng huà dòng wù yóu', 'mixed', 'Species unstated; may be lard.'],
    ['动物胶', 'animal', 'animal glue', 'dòng wù jiāo', 'mixed', 'Hide or bone glue; species unstated.'],
    ['动物蛋白', 'animal', 'animal protein', 'dòng wù dàn bái', 'mixed', 'Species unstated.'],
    ['明胶', 'animal', 'gelatin', 'míng jiāo', 'mixed', 'Always animal; in China usually pig or cattle skin or bone. Halal only if the source is stated.'],
    ['骨粉', 'animal', 'bone meal', 'gǔ fěn', 'mixed', 'Ground animal bone.'],
    ['骨炭', 'animal', 'bone char', 'gǔ tàn', 'mixed', 'Charred animal bone, used as pigment and filter.'],
    ['骨胶', 'animal', 'bone glue', 'gǔ jiāo', 'mixed', 'Glue from animal bone; species unstated.'],
    ['骨胶原', 'animal', 'bone collagen', 'gǔ jiāo yuán', 'mixed', 'Collagen from animal bone, often cattle or pig.'],
    ['软骨素', 'animal', 'chondroitin', 'ruǎn gǔ sù', 'mixed', 'From cartilage of shark, cattle, pig or chicken.'],
    ['硫酸软骨素', 'animal', 'chondroitin sulfate', 'liú suān ruǎn gǔ sù', 'mixed', 'From cartilage of shark, cattle, pig or chicken.'],
    ['弹性蛋白', 'animal', 'elastin', 'tán xìng dàn bái', 'mixed', 'Usually hydrolysed from cattle or fish tissue.'],
    ['角蛋白', 'animal', 'keratin', 'jiǎo dàn bái', 'mixed', 'From wool, feathers, hooves or horn; species usually unstated.'],
    ['水解角蛋白', 'animal', 'hydrolysed keratin', 'shuǐ jiě jiǎo dàn bái', 'mixed', 'From wool, feathers or horn.'],
    ['胎盘', 'animal', 'placenta', 'tāi pán', 'mixed', 'Species unstated; commonly sheep or pig.'],
    ['胎盘提取物', 'animal', 'placenta extract', 'tāi pán tí qǔ wù', 'mixed', 'Species unstated; commonly sheep or pig.'],
    ['胎盘素', 'animal', 'placenta extract', 'tāi pán sù', 'mixed', 'Species unstated; commonly sheep or pig.'],
    ['脐带', 'animal', 'umbilical cord', 'qí dài', 'mixed', 'Umbilical cord extract; species unstated.'],
    ['Gelatin', 'animal', 'gelatin', '', 'mixed', 'Always animal; usually pig or cattle.'],
    ['Keratin', 'animal', 'keratin', '', 'mixed', 'From wool, feathers or horn.'],
    ['Placenta', 'animal', 'placenta', '', 'mixed', 'Species unstated.'],
    ['Mink Oil', 'animal', 'mink oil', '', 'mixed', 'Mink fat.'],

    // ================= HUMAN
    ['人胎盘', 'animal', 'human placenta', 'rén tāi pán', 'human', 'Human tissue; banned in Chinese cosmetics and impermissible to use.'],
    ['母乳', 'animal', 'human breast milk', 'mǔ rǔ', 'human', 'Human-derived.'],

    // ================= MARINE
    ['鲸蜡', 'animal', 'spermaceti', 'jīng là', 'marine', 'Wax from the sperm whale. Not 鲸蜡醇 (cetyl alcohol).'],
    ['鲸油', 'animal', 'whale oil', 'jīng yóu', 'marine', 'Whale fat.'],
    ['龙涎香', 'animal', 'ambergris', 'lóng xián xiāng', 'marine', 'Sperm whale secretion; most perfumes use synthetic ambrox instead.'],
    ['鱼油', 'animal', 'fish oil', 'yú yóu', 'marine', 'Fish oil.'],
    ['深海鱼油', 'animal', 'deep-sea fish oil', 'shēn hǎi yú yóu', 'marine', 'Fish oil.'],
    ['鱼肝油', 'animal', 'cod liver oil', 'yú gān yóu', 'marine', 'Fish liver oil.'],
    ['鲨鱼肝油', 'animal', 'shark liver oil', 'shā yú gān yóu', 'marine', 'Shark liver oil.'],
    ['鲨鱼软骨', 'animal', 'shark cartilage', 'shā yú ruǎn gǔ', 'marine', 'Shark cartilage.'],
    ['鱼胶原', 'animal', 'fish collagen', 'yú jiāo yuán', 'marine', 'Collagen from fish skin or scales.'],
    ['鱼胶原蛋白', 'animal', 'fish collagen', 'yú jiāo yuán dàn bái', 'marine', 'Collagen from fish skin or scales.'],
    ['海洋胶原', 'animal', 'marine collagen', 'hǎi yáng jiāo yuán', 'marine', 'Collagen from fish.'],
    ['鱼鳞', 'animal', 'fish scale', 'yú lín', 'marine', 'Fish scale, source of collagen and pearl pigment.'],
    ['鱼胶', 'animal', 'fish glue / isinglass', 'yú jiāo', 'marine', 'Glue from fish swim bladder or skin.'],
    ['鱼鳔胶', 'animal', 'isinglass', 'yú biào jiāo', 'marine', 'Fish swim-bladder glue.'],
    ['鱼子酱', 'animal', 'caviar', 'yú zǐ jiàng', 'marine', 'Fish roe extract in luxury creams.'],
    ['鱼子', 'animal', 'fish roe', 'yú zǐ', 'marine', 'Fish eggs.'],
    ['鱼子酱提取物', 'animal', 'caviar extract', 'yú zǐ jiàng tí qǔ wù', 'marine', 'Fish roe extract.'],
    ['鱼精蛋白', 'animal', 'protamine', 'yú jīng dàn bái', 'marine', 'Protein from fish milt.'],
    ['鸟嘌呤', 'animal', 'guanine (CI 75170)', 'niǎo piào lìng', 'marine', 'Pearlescent pigment, usually from fish scales.'],
    ['珍珠', 'animal', 'pearl', 'zhēn zhū', 'marine', 'Mollusc product. Not 珍珠岩 (perlite) or 人造珍珠.'],
    ['珍珠粉', 'animal', 'pearl powder', 'zhēn zhū fěn', 'marine', 'Ground pearl from molluscs.'],
    ['水解珍珠', 'animal', 'hydrolysed pearl', 'shuǐ jiě zhēn zhū', 'marine', 'Mollusc product.'],
    ['珍珠母', 'animal', 'mother of pearl', 'zhēn zhū mǔ', 'marine', 'Mollusc shell nacre.'],
    ['牡蛎', 'animal', 'oyster', 'mǔ lì', 'marine', 'Oyster or oyster shell.'],
    ['海参', 'animal', 'sea cucumber', 'hǎi shēn', 'marine', 'Sea cucumber extract.'],
    ['Guanine', 'animal', 'guanine', '', 'marine', 'Pearlescent pigment, usually from fish scales.'],

    // ================= INSECT
    ['胭脂虫红', 'animal', 'carmine (CI 75470)', 'yān zhī chóng hóng', 'insect', 'Red dye from cochineal insects.'],
    ['胭脂虫', 'animal', 'cochineal', 'yān zhī chóng', 'insect', 'Insect dye.'],
    ['CI 75470', 'animal', 'carmine', '', 'insect', 'Cochineal insect dye.'],
    ['CI75470', 'animal', 'carmine', '', 'insect', 'Cochineal insect dye.'],
    ['Carmine', 'animal', 'carmine', '', 'insect', 'Cochineal insect dye.'],
    ['紫胶', 'animal', 'shellac / lac', 'zǐ jiāo', 'insect', 'Lac insect resin, used in nail polish, mascara and coatings.'],
    ['虫胶', 'animal', 'shellac', 'chóng jiāo', 'insect', 'Lac insect resin.'],
    ['Shellac', 'animal', 'shellac', '', 'insect', 'Lac insect resin.'],
    ['蚕丝', 'animal', 'silk', 'cán sī', 'insect', 'Silkworm silk; some 蚕丝面膜 sheets are actually synthetic.'],
    ['蚕丝蛋白', 'animal', 'silk protein', 'cán sī dàn bái', 'insect', 'Silkworm protein.'],
    ['丝蛋白', 'animal', 'silk protein', 'sī dàn bái', 'insect', 'Silkworm protein.'],
    ['丝素', 'animal', 'silk fibroin', 'sī sù', 'insect', 'Silkworm protein.'],
    ['丝胶', 'animal', 'sericin', 'sī jiāo', 'insect', 'Silkworm protein.'],
    ['水解蚕丝', 'animal', 'hydrolysed silk', 'shuǐ jiě cán sī', 'insect', 'Silkworm protein.'],
    ['僵蚕', 'animal', 'dried silkworm', 'jiāng cán', 'insect', 'Traditional whitening ingredient.'],
    ['Silk', 'animal', 'silk', '', 'insect', 'Silkworm.'],
    ['Sericin', 'animal', 'sericin', '', 'insect', 'Silkworm protein.'],

    // ================= BEE
    ['蜂蜡', 'animal', 'beeswax', 'fēng là', 'bee', 'Bee product; common in lip balm, mascara and creams.'],
    ['蜂蜜', 'animal', 'honey', 'fēng mì', 'bee', 'Bee product.'],
    ['蜂王浆', 'animal', 'royal jelly', 'fēng wáng jiāng', 'bee', 'Bee product.'],
    ['蜂乳', 'animal', 'royal jelly', 'fēng rǔ', 'bee', 'Bee product.'],
    ['蜂胶', 'animal', 'propolis', 'fēng jiāo', 'bee', 'Bee resin; common in toothpaste.'],
    ['蜂毒', 'animal', 'bee venom', 'fēng dú', 'bee', 'Bee product.'],
    ['蜂花粉', 'animal', 'bee pollen', 'fēng huā fěn', 'bee', 'Pollen collected by bees.'],
    ['Beeswax', 'animal', 'beeswax', '', 'bee', 'Bee product.'],
    ['Cera Alba', 'animal', 'beeswax (INCI)', '', 'bee', 'Bee product.'],
    ['Honey', 'animal', 'honey', '', 'bee', 'Bee product.'],
    ['Propolis', 'animal', 'propolis', '', 'bee', 'Bee product.'],
    ['Royal Jelly', 'animal', 'royal jelly', '', 'bee', 'Bee product.'],

    // ================= SNAIL
    ['蜗牛', 'animal', 'snail', 'wō niú', 'snail', 'Snail-derived.'],
    ['蜗牛分泌物滤液', 'animal', 'snail secretion filtrate', 'wō niú fēn mì wù lǜ yè', 'snail', 'Snail mucin.'],
    ['Snail Secretion Filtrate', 'animal', 'snail mucin', '', 'snail', 'Snail-derived.'],

    // ================= BIRD / EGG
    ['燕窝', 'animal', 'edible bird nest', 'yàn wō', 'bird', 'Swiftlet saliva nest. Not 雪燕 (plant gum).'],
    ['燕窝提取物', 'animal', 'bird nest extract', 'yàn wō tí qǔ wù', 'bird', 'Swiftlet saliva nest.'],
    ['鸡冠', 'animal', 'rooster comb', 'jī guān', 'bird', 'Source of hyaluronic acid. Not 鸡冠花 (celosia flower).'],
    ['鸡冠提取物', 'animal', 'rooster comb extract', 'jī guān tí qǔ wù', 'bird', 'Rooster comb.'],
    ['鸸鹋油', 'animal', 'emu oil', 'ér miáo yóu', 'bird', 'Emu fat.'],
    ['鸵鸟油', 'animal', 'ostrich oil', 'tuó niǎo yóu', 'bird', 'Ostrich fat.'],
    ['羽绒', 'animal', 'down feathers', 'yǔ róng', 'bird', 'Duck or goose down.'],
    ['Emu Oil', 'animal', 'emu oil', '', 'bird', 'Emu fat.'],
    ['鸡蛋', 'animal', 'egg', 'jī dàn', 'egg', 'Egg. Not 鸡蛋花 (frangipani).'],
    ['蛋清', 'animal', 'egg white', 'dàn qīng', 'egg', 'Egg.'],
    ['蛋黄', 'animal', 'egg yolk', 'dàn huáng', 'egg', 'Egg.'],
    ['蛋黄油', 'animal', 'egg yolk oil', 'dàn huáng yóu', 'egg', 'Egg.'],
    ['卵清蛋白', 'animal', 'ovalbumin', 'luǎn qīng dàn bái', 'egg', 'Egg-white protein.'],
    ['卵黄', 'animal', 'egg yolk', 'luǎn huáng', 'egg', 'Egg.'],
    ['蛋壳膜', 'animal', 'eggshell membrane', 'dàn ké mó', 'egg', 'Egg.'],
    ['溶菌酶', 'animal', 'lysozyme', 'róng jūn méi', 'egg', 'Usually extracted from hen egg white.'],

    // ================= FOOD-DICTIONARY OVERRIDES: these are 'ok' (halal) in the food dictionary, but on a non-food label
    // they are animal products; without these rows the longer food term would hide the animal term (longest match wins).
    ['生牛乳', 'animal', 'raw cow milk', 'shēng niú rǔ', 'dairy', 'Milk ingredient.'],
    ['生牛奶', 'animal', 'raw cow milk', 'shēng niú nǎi', 'dairy', 'Milk ingredient.'],
    ['牦牛奶', 'animal', 'yak milk', 'máo niú nǎi', 'dairy', 'Milk ingredient.'],
    ['牦牛乳', 'animal', 'yak milk', 'máo niú rǔ', 'dairy', 'Milk ingredient.'],
    ['牛奶粉', 'animal', 'milk powder', 'niú nǎi fěn', 'dairy', 'Dried milk.'],
    ['牛乳粉', 'animal', 'milk powder', 'niú rǔ fěn', 'dairy', 'Dried milk.'],
    ['羊奶粉', 'animal', 'goat milk powder', 'yáng nǎi fěn', 'dairy', 'Dried goat milk; common in goat-milk soaps and lotions.'],
    ['羊乳粉', 'animal', 'goat milk powder', 'yáng rǔ fěn', 'dairy', 'Dried goat milk.'],
    ['驼奶', 'animal', 'camel milk', 'tuó nǎi', 'dairy', 'Milk ingredient.'],
    ['驼乳', 'animal', 'camel milk', 'tuó rǔ', 'dairy', 'Milk ingredient.'],
    ['驼奶粉', 'animal', 'camel milk powder', 'tuó nǎi fěn', 'dairy', 'Dried camel milk.'],
    ['乳粉', 'animal', 'milk powder', 'rǔ fěn', 'dairy', 'Dried milk.'],
    ['全脂奶粉', 'animal', 'whole milk powder', 'quán zhī nǎi fěn', 'dairy', 'Dried milk.'],
    ['脱脂奶粉', 'animal', 'skimmed milk powder', 'tuō zhī nǎi fěn', 'dairy', 'Dried milk.'],
    ['全脂乳粉', 'animal', 'whole milk powder', 'quán zhī rǔ fěn', 'dairy', 'Dried milk.'],
    ['脱脂乳粉', 'animal', 'skimmed milk powder', 'tuō zhī rǔ fěn', 'dairy', 'Dried milk.'],
    ['酸奶粉', 'animal', 'yoghurt powder', 'suān nǎi fěn', 'dairy', 'Dried fermented milk.'],
    ['发酵乳', 'animal', 'fermented milk', 'fā jiào rǔ', 'dairy', 'Fermented milk.'],
    ['炼乳', 'animal', 'condensed milk', 'liàn rǔ', 'dairy', 'Milk ingredient.'],
    ['稀奶油', 'animal', 'dairy cream', 'xī nǎi yóu', 'dairy', 'Milk fat.'],
    ['淡奶油', 'animal', 'whipping cream', 'dàn nǎi yóu', 'dairy', 'Milk fat.'],
    ['无水奶油', 'animal', 'anhydrous milk fat', 'wú shuǐ nǎi yóu', 'dairy', 'Milk fat.'],
    ['乳脂肪', 'animal', 'milk fat', 'rǔ zhī fáng', 'dairy', 'Milk fat.'],
    ['乳清粉', 'animal', 'whey powder', 'rǔ qīng fěn', 'dairy', 'Milk by-product.'],
    ['分离乳清蛋白', 'animal', 'whey protein isolate', 'fēn lí rǔ qīng dàn bái', 'dairy', 'Milk protein.'],
    ['浓缩乳清蛋白', 'animal', 'whey protein concentrate', 'nóng suō rǔ qīng dàn bái', 'dairy', 'Milk protein.'],
    ['水解乳清蛋白', 'animal', 'hydrolysed whey protein', 'shuǐ jiě rǔ qīng dàn bái', 'dairy', 'Milk protein.'],
    ['酪蛋白酸钠', 'animal', 'sodium caseinate', 'lào dàn bái suān nà', 'dairy', 'Milk protein.'],
    ['酪蛋白酸钙', 'animal', 'calcium caseinate', 'lào dàn bái suān gài', 'dairy', 'Milk protein.'],
    ['乳钙', 'animal', 'milk calcium', 'rǔ gài', 'dairy', 'Calcium extracted from whey.'],
    ['骨桥蛋白', 'animal', 'osteopontin', 'gǔ qiáo dàn bái', 'dairy', 'Protein isolated from cow milk.'],
    ['乳糖酸', 'animal', 'lactobionic acid', 'rǔ táng suān', 'dairy', 'Made by oxidising milk lactose.'],
    ['乳糖醇', 'animal', 'lactitol', 'rǔ táng chún', 'dairy', 'Sugar alcohol made from milk lactose.'],
    ['鸡蛋粉', 'animal', 'egg powder', 'jī dàn fěn', 'egg', 'Egg.'],
    ['鸡蛋液', 'animal', 'liquid egg', 'jī dàn yè', 'egg', 'Egg.'],
    ['鸡蛋黄', 'animal', 'egg yolk', 'jī dàn huáng', 'egg', 'Egg.'],
    ['鸡蛋白', 'animal', 'egg white', 'jī dàn bái', 'egg', 'Egg.'],
    ['全蛋粉', 'animal', 'whole egg powder', 'quán dàn fěn', 'egg', 'Egg.'],
    ['全蛋液', 'animal', 'liquid whole egg', 'quán dàn yè', 'egg', 'Egg.'],
    ['蛋液', 'animal', 'liquid egg', 'dàn yè', 'egg', 'Egg.'],
    ['蛋黄粉', 'animal', 'egg yolk powder', 'dàn huáng fěn', 'egg', 'Egg.'],
    ['蛋黄液', 'animal', 'liquid egg yolk', 'dàn huáng yè', 'egg', 'Egg.'],
    ['蛋清粉', 'animal', 'egg white powder', 'dàn qīng fěn', 'egg', 'Egg.'],
    ['蛋黄卵磷脂', 'animal', 'egg yolk lecithin', 'dàn huáng luǎn lín zhī', 'egg', 'Lecithin from egg yolk.'],
    ['蛋壳', 'animal', 'eggshell', 'dàn ké', 'egg', 'Eggshell powder, used as an abrasive.'],
    ['鸭蛋', 'animal', 'duck egg', 'yā dàn', 'egg', 'Egg.'],
    ['鹌鹑蛋', 'animal', 'quail egg', 'ān chún dàn', 'egg', 'Egg; quail-egg masks and creams.'],
    ['鸵鸟蛋', 'animal', 'ostrich egg', 'tuó niǎo dàn', 'egg', 'Egg.'],
    ['鱼', 'animal', 'fish (species unstated)', 'yú', 'marine', 'Any fish-named material in a non-food list is fish-derived. Not 鱼腥草 or 金鱼草 (plants).'],
    ['鲑鱼', 'animal', 'salmon', 'guī yú', 'marine', 'Salmon roe, milt (PDRN) or cartilage extracts.'],
    ['三文鱼', 'animal', 'salmon', 'sān wén yú', 'marine', 'Salmon roe, milt (PDRN) or cartilage extracts.'],
    ['鳕鱼', 'animal', 'cod', 'xuě yú', 'marine', 'Cod skin collagen or cod liver oil.'],
    ['金枪鱼', 'animal', 'tuna', 'jīn qiāng yú', 'marine', 'Tuna oil or collagen.'],
    ['鲨鱼', 'animal', 'shark', 'shā yú', 'marine', 'Shark liver oil or cartilage.'],
    ['鳗鱼', 'animal', 'eel', 'mán yú', 'marine', 'Eel-derived.'],
    ['海鱼', 'animal', 'sea fish', 'hǎi yú', 'marine', 'Fish-derived.'],
    ['鱼皮', 'animal', 'fish skin', 'yú pí', 'marine', 'Source of fish collagen and gelatin.'],
    ['鱼骨', 'animal', 'fish bone', 'yú gǔ', 'marine', 'Fish bone.'],
    ['鱼骨粉', 'animal', 'fish bone powder', 'yú gǔ fěn', 'marine', 'Ground fish bone.'],
    ['鱼粉', 'animal', 'fish meal', 'yú fěn', 'marine', 'Ground fish.'],
    ['鱼鳔', 'animal', 'fish swim bladder', 'yú biào', 'marine', 'Source of isinglass and collagen.'],
    ['木鱼花', 'animal', 'bonito flakes', 'mù yú huā', 'marine', 'Dried fish.'],
    ['花胶', 'animal', 'dried fish maw', 'huā jiāo', 'marine', 'Fish swim bladder; sold as a collagen ingredient.'],
    ['鱼籽', 'animal', 'fish roe', 'yú zǐ', 'marine', 'Fish eggs.'],
    ['鱼明胶', 'animal', 'fish gelatin', 'yú míng jiāo', 'marine', 'Gelatin from fish skin or scales.'],
    ['鱼胶粉', 'animal', 'fish gelatin powder', 'yú jiāo fěn', 'marine', 'Gelatin from fish skin or scales.'],
    ['鱼皮胶原', 'animal', 'fish-skin collagen', 'yú pí jiāo yuán', 'marine', 'Collagen from fish skin.'],
    ['鱼胶原蛋白肽', 'animal', 'fish collagen peptide', 'yú jiāo yuán dàn bái tài', 'marine', 'Collagen from fish skin or scales.'],
    ['软骨', 'animal', 'cartilage', 'ruǎn gǔ', 'mixed', 'Animal cartilage (shark, cattle, pig or chicken).'],
    ['蛋白聚糖', 'animal', 'proteoglycan', 'dàn bái jù táng', 'mixed', 'Cosmetic grades are extracted from salmon nasal cartilage or other animal cartilage.'],
    ['蜂巢', 'animal', 'honeycomb', 'fēng cháo', 'bee', 'Bee product.'],
    ['鹿角胶', 'animal', 'deer antler glue', 'lù jiǎo jiāo', 'mixed', 'Gelatin boiled from deer antler.'],
    ['胭脂虫红酸', 'animal', 'carminic acid', 'yān zhī chóng hóng suān', 'insect', 'Cochineal insect dye.'],
    ['紫胶红', 'animal', 'lac dye', 'zǐ jiāo hóng', 'insect', 'Red dye from the lac insect.'],
    ['虫胶红', 'animal', 'lac dye', 'chóng jiāo hóng', 'insect', 'Red dye from the lac insect.'],
    ['CI 75170', 'animal', 'guanine', '', 'marine', 'Pearlescent pigment, usually from fish scales.'],
    ['CI75170', 'animal', 'guanine', '', 'marine', 'Pearlescent pigment, usually from fish scales.'],
    ['Elastin', 'animal', 'elastin', '', 'mixed', 'Usually from cattle or fish tissue.'],
    // the food dictionary marks these 'haram' (impermissible to eat); on a non-food label they are non-pig animal material
    ['雪蛤', 'animal', 'forest frog oviduct (hasma)', 'xuě há', 'mixed', 'Frog-derived; used in 雪蛤 creams.'],
    ['蛙油', 'animal', 'frog oil', 'wā yóu', 'mixed', 'Frog-derived.'],
    ['林蛙油', 'animal', 'forest frog oil', 'lín wā yóu', 'mixed', 'Frog-derived.'],
    ['驴皮', 'animal', 'donkey hide', 'lǘ pí', 'mixed', 'Donkey hide, the raw material of 阿胶.'],
    ['蛤蚧', 'animal', 'tokay gecko', 'gé jiè', 'mixed', 'Dried lizard used in traditional preparations.'],
    ['鳄鱼', 'animal', 'crocodile', 'è yú', 'mixed', 'Crocodile-derived.'],

    // ================= SOURCE UNSTATED (unsure): animal, plant or synthetic
    ['甘油', 'unsure', 'glycerin', 'gān yóu', 'mixed', 'From plant oils, petrochemicals or animal fat; most cosmetic glycerin is plant or synthetic.'],
    ['丙三醇', 'unsure', 'glycerol', 'bǐng sān chún', 'mixed', 'Same as 甘油.'],
    ['Glycerin', 'unsure', 'glycerin', '', 'mixed', 'Plant, synthetic or animal fat.'],
    ['Glycerine', 'unsure', 'glycerin', '', 'mixed', 'Plant, synthetic or animal fat.'],
    ['硬脂酸', 'unsure', 'stearic acid', 'yìng zhī suān', 'mixed', 'From palm or other plant oils, or from tallow.'],
    ['硬脂酸镁', 'unsure', 'magnesium stearate', 'yìng zhī suān měi', 'mixed', 'Stearic acid salt; plant or tallow.'],
    ['硬脂酸锌', 'unsure', 'zinc stearate', 'yìng zhī suān xīn', 'mixed', 'Stearic acid salt; plant or tallow.'],
    ['硬脂酸钠', 'unsure', 'sodium stearate', 'yìng zhī suān nà', 'mixed', 'Soap; plant or tallow.'],
    ['硬脂酰', 'unsure', 'stearoyl-', 'yìng zhī xiān', 'mixed', 'Stearic-acid derivative; plant or tallow.'],
    ['甘油硬脂酸酯', 'unsure', 'glyceryl stearate', 'gān yóu yìng zhī suān zhǐ', 'mixed', 'Plant or animal fat.'],
    ['硬脂酸甘油酯', 'unsure', 'glyceryl stearate', 'yìng zhī suān gān yóu zhǐ', 'mixed', 'Plant or animal fat.'],
    ['单硬脂酸甘油酯', 'unsure', 'glyceryl monostearate', 'dān yìng zhī suān gān yóu zhǐ', 'mixed', 'Plant or animal fat.'],
    ['硬脂醇', 'unsure', 'stearyl alcohol', 'yìng zhī chún', 'mixed', 'Fatty alcohol from plant oil or tallow.'],
    ['Stearic Acid', 'unsure', 'stearic acid', '', 'mixed', 'Plant or tallow.'],
    ['Stearate', 'unsure', 'stearate', '', 'mixed', 'Stearic-acid ester or salt; plant or tallow.'],
    ['Stearyl Alcohol', 'unsure', 'stearyl alcohol', '', 'mixed', 'Plant or tallow.'],
    ['鲸蜡醇', 'unsure', 'cetyl alcohol', 'jīng là chún', 'mixed', 'Named after spermaceti but today made from palm or coconut oil or synthetically; tallow sources exist.'],
    ['鲸蜡硬脂醇', 'unsure', 'cetearyl alcohol', 'jīng là yìng zhī chún', 'mixed', 'Fatty alcohol; usually plant, tallow possible.'],
    ['鲸蜡硬脂基', 'unsure', 'cetearyl-', 'jīng là yìng zhī jī', 'mixed', 'Fatty-alcohol derivative; usually plant.'],
    ['鲸蜡基', 'unsure', 'cetyl-', 'jīng là jī', 'mixed', 'Fatty-alcohol derivative; not whale.'],
    ['鲸蜡酯', 'unsure', 'cetyl esters', 'jīng là zhǐ', 'mixed', 'Synthetic spermaceti substitute; fatty acids may be plant or animal.'],
    ['Cetyl Alcohol', 'unsure', 'cetyl alcohol', '', 'mixed', 'Usually plant or synthetic.'],
    ['Cetearyl Alcohol', 'unsure', 'cetearyl alcohol', '', 'mixed', 'Usually plant or synthetic.'],
    ['棕榈酸', 'unsure', 'palmitic acid', 'zōng lǘ suān', 'mixed', 'Mostly palm oil; also in tallow.'],
    ['肉豆蔻酸', 'unsure', 'myristic acid', 'ròu dòu kòu suān', 'mixed', 'Coconut, palm kernel or animal fat.'],
    ['油酸', 'unsure', 'oleic acid', 'yóu suān', 'mixed', 'Olive or other plant oil, or tallow.'],
    ['油醇', 'unsure', 'oleyl alcohol', 'yóu chún', 'mixed', 'Plant oil or tallow.'],
    ['脂肪酸', 'unsure', 'fatty acids', 'zhī fáng suān', 'mixed', 'Plant oil or animal fat; source unstated.'],
    ['皂基', 'unsure', 'soap base', 'zào jī', 'mixed', 'Made from plant oil or tallow; ask which.'],
    ['脂肪酸钠', 'unsure', 'sodium fatty acids (soap)', 'zhī fáng suān nà', 'mixed', 'Soap; plant oil or tallow.'],
    ['脂肪酸钾', 'unsure', 'potassium fatty acids (soap)', 'zhī fáng suān jiǎ', 'mixed', 'Soft soap; plant oil or tallow.'],
    ['钙皂', 'unsure', 'calcium soap', 'gài zào', 'mixed', 'Fatty-acid salt; plant oil or tallow.'],
    ['辛酸/癸酸甘油三酯', 'unsure', 'caprylic/capric triglyceride', 'xīn suān guǐ suān gān yóu sān zhǐ', 'mixed', 'Almost always coconut or palm kernel oil.'],
    ['Caprylic/Capric Triglyceride', 'unsure', 'caprylic/capric triglyceride', '', 'mixed', 'Almost always coconut or palm kernel oil.'],
    ['胶原', 'unsure', 'collagen', 'jiāo yuán', 'mixed', 'Animal (pig, cattle, fish) unless stated recombinant.'],
    ['胶原蛋白', 'unsure', 'collagen', 'jiāo yuán dàn bái', 'mixed', 'Animal (pig, cattle, fish) unless stated recombinant 重组.'],
    ['水解胶原', 'unsure', 'hydrolysed collagen', 'shuǐ jiě jiāo yuán', 'mixed', 'Animal (pig, cattle, fish) unless stated recombinant.'],
    ['胶原肽', 'unsure', 'collagen peptide', 'jiāo yuán tài', 'mixed', 'Animal unless stated recombinant.'],
    ['Collagen', 'unsure', 'collagen', '', 'mixed', 'Animal unless stated recombinant.'],
    ['透明质酸钠', 'unsure', 'sodium hyaluronate', 'tòu míng zhì suān nà', 'mixed', 'Chinese supply is mostly microbial fermentation; rooster comb is the animal source.'],
    ['透明质酸', 'unsure', 'hyaluronic acid', 'tòu míng zhì suān', 'mixed', 'Mostly fermentation; rooster comb possible.'],
    ['玻尿酸', 'unsure', 'hyaluronic acid', 'bō niào suān', 'mixed', 'Mostly fermentation; rooster comb possible.'],
    ['Sodium Hyaluronate', 'unsure', 'sodium hyaluronate', '', 'mixed', 'Mostly fermentation; rooster comb possible.'],
    ['Hyaluronic Acid', 'unsure', 'hyaluronic acid', '', 'mixed', 'Mostly fermentation; rooster comb possible.'],
    ['角鲨烷', 'unsure', 'squalane', 'jiǎo shā wán', 'marine', 'From olive, sugarcane or shark liver.'],
    ['角鲨烯', 'unsure', 'squalene', 'jiǎo shā xī', 'marine', 'From olive, amaranth or shark liver.'],
    ['燕窝酸', 'unsure', 'sialic acid (N-acetylneuraminic acid)', 'yàn wō suān', 'bird', 'Made by fermentation or synthesis, or extracted from bird nest.'],
    ['多聚脱氧核糖核苷酸', 'unsure', 'PDRN (polydeoxyribonucleotide)', 'duō jù tuō yǎng hé táng hé gān suān', 'marine', 'Usually from salmon or trout milt; plant-derived grades are also sold.'],
    ['脱氧核糖核酸钠', 'unsure', 'sodium DNA', 'tuō yǎng hé táng hé suān nà', 'marine', 'Usually from salmon or trout milt.'],
    ['PDRN', 'unsure', 'PDRN', '', 'marine', 'Usually from salmon or trout milt; plant-derived grades are also sold.'],
    ['麝香酮', 'unsure', 'muscone', 'shè xiāng tóng', 'mixed', 'The odour compound of musk; commercial muscone is almost always synthetic.'],
    ['鲨肝醇', 'unsure', 'batyl alcohol', 'shā gān chún', 'marine', 'Historically shark liver; now mostly synthetic.'],
    ['Squalane', 'unsure', 'squalane', '', 'marine', 'Olive, sugarcane or shark.'],
    ['Squalene', 'unsure', 'squalene', '', 'marine', 'Olive, amaranth or shark.'],
    ['甲壳素', 'unsure', 'chitin', 'jiǎ qiào sù', 'marine', 'Usually shrimp or crab shell; fungal grades exist.'],
    ['壳聚糖', 'unsure', 'chitosan', 'ké jù táng', 'marine', 'Usually shrimp or crab shell; fungal grades exist.'],
    ['氨基葡萄糖', 'unsure', 'glucosamine', 'ān jī pú táo táng', 'marine', 'Shellfish shell or fermentation.'],
    ['卵磷脂', 'unsure', 'lecithin', 'luǎn lín zhī', 'mixed', 'From soy, sunflower or egg yolk.'],
    ['Lecithin', 'unsure', 'lecithin', '', 'mixed', 'Soy, sunflower or egg.'],
    ['尿囊素', 'unsure', 'allantoin', 'niào náng sù', 'mixed', 'Nearly always synthetic; historically animal or comfrey.'],
    ['Allantoin', 'unsure', 'allantoin', '', 'mixed', 'Nearly always synthetic.'],
    ['神经酰胺', 'unsure', 'ceramide', 'shén jīng xiān àn', 'mixed', 'Now mostly synthetic, yeast or plant; historically bovine.'],
    ['胆固醇', 'unsure', 'cholesterol', 'dǎn gù chún', 'mixed', 'Usually from lanolin; plant-derived grades exist.'],
    ['胆甾醇', 'unsure', 'cholesterol (INCI name)', 'dǎn zāi chún', 'mixed', 'The Chinese INCI name for cholesterol; usually from lanolin.'],
    ['Ceramide', 'unsure', 'ceramide', '', 'mixed', 'Now mostly synthetic, yeast or plant; historically bovine.'],
    ['Cholesterol', 'unsure', 'cholesterol', '', 'mixed', 'Usually from lanolin.'],
    ['维生素D3', 'unsure', 'vitamin D3', 'wéi shēng sù D3', 'mixed', 'Usually from lanolin; lichen-derived grades exist.'],
    ['胆钙化醇', 'unsure', 'cholecalciferol (vitamin D3)', 'dǎn gài huà chún', 'mixed', 'Usually from lanolin.'],
    ['生物素', 'unsure', 'biotin', 'shēng wù sù', 'mixed', 'Nearly always synthetic.'],
    ['羟基磷灰石', 'unsure', 'hydroxyapatite', 'qiǎng jī lín huī shí', 'mixed', 'Synthetic or from bone; toothpaste ingredient.'],

    // ================= ALCOHOLS (informational, acceptable)
    ['乙醇', 'alcohol', 'ethanol', 'yǐ chún', 'alcohol', 'Alcohol; acceptable in non-food items.'],
    ['酒精', 'alcohol', 'alcohol', 'jiǔ jīng', 'alcohol', 'Alcohol; acceptable in non-food items.'],
    ['变性乙醇', 'alcohol', 'denatured alcohol', 'biàn xìng yǐ chún', 'alcohol', 'Alcohol; acceptable in non-food items.'],
    ['变性酒精', 'alcohol', 'denatured alcohol', 'biàn xìng jiǔ jīng', 'alcohol', 'Alcohol; acceptable in non-food items.'],
    ['无水乙醇', 'alcohol', 'anhydrous ethanol', 'wú shuǐ yǐ chún', 'alcohol', 'Alcohol; acceptable in non-food items.'],
    ['异丙醇', 'alcohol', 'isopropyl alcohol', 'yì bǐng chún', 'alcohol', 'Synthetic alcohol; acceptable.'],
    ['苯甲醇', 'alcohol', 'benzyl alcohol', 'běn jiǎ chún', 'alcohol', 'Preservative / solvent; acceptable.'],
    ['苯乙醇', 'alcohol', 'phenethyl alcohol', 'běn yǐ chún', 'alcohol', 'Fragrance / preservative; acceptable.'],
    ['苯氧乙醇', 'alcohol', 'phenoxyethanol', 'běn yǎng yǐ chún', 'alcohol', 'Synthetic preservative; acceptable.'],
    ['丁二醇', 'alcohol', 'butylene glycol', 'dīng èr chún', 'alcohol', 'Glycol humectant; acceptable.'],
    ['戊二醇', 'alcohol', 'pentylene glycol', 'wù èr chún', 'alcohol', 'Glycol humectant; acceptable.'],
    ['己二醇', 'alcohol', 'hexylene / hexanediol', 'jǐ èr chún', 'alcohol', 'Glycol; acceptable.'],
    ['丙二醇', 'alcohol', 'propylene glycol', 'bǐng èr chún', 'alcohol', 'Glycol humectant; acceptable.'],
    ['双丙甘醇', 'alcohol', 'dipropylene glycol (INCI name)', 'shuāng bǐng gān chún', 'alcohol', 'Glycol solvent; acceptable.'],
    ['二丙二醇', 'alcohol', 'dipropylene glycol', 'èr bǐng èr chún', 'alcohol', 'Glycol solvent; acceptable.'],
    ['辛甘醇', 'alcohol', 'caprylyl glycol', 'xīn gān chún', 'alcohol', 'Synthetic glycol; acceptable.'],
    ['聚乙二醇', 'alcohol', 'polyethylene glycol (PEG)', 'jù yǐ èr chún', 'alcohol', 'Synthetic; acceptable.'],
    ['乙醇胺', 'alcohol', 'ethanolamine', 'yǐ chún àn', 'alcohol', 'Synthetic; acceptable.'],
    ['三乙醇胺', 'alcohol', 'triethanolamine', 'sān yǐ chún àn', 'alcohol', 'Synthetic pH adjuster; acceptable.'],
    ['Alcohol', 'alcohol', 'alcohol', '', 'alcohol', 'Acceptable in non-food items.'],
    ['Alcohol Denat.', 'alcohol', 'denatured alcohol', '', 'alcohol', 'Acceptable in non-food items.'],
    ['Ethanol', 'alcohol', 'ethanol', '', 'alcohol', 'Acceptable in non-food items.'],
    ['Isopropyl Alcohol', 'alcohol', 'isopropyl alcohol', '', 'alcohol', 'Acceptable.'],
    ['Benzyl Alcohol', 'alcohol', 'benzyl alcohol', '', 'alcohol', 'Acceptable.'],
    ['Phenoxyethanol', 'alcohol', 'phenoxyethanol', '', 'alcohol', 'Acceptable.'],
    ['Butylene Glycol', 'alcohol', 'butylene glycol', '', 'alcohol', 'Acceptable.'],
    ['Propylene Glycol', 'alcohol', 'propylene glycol', '', 'alcohol', 'Acceptable.'],

    // ================= LOOKALIKES: plant / mineral / synthetic (ok)
    ['植物甘油', 'ok', 'vegetable glycerin', 'zhí wù gān yóu', 'plant', 'Stated plant source.'],
    ['乙基己基甘油', 'ok', 'ethylhexylglycerin', 'yǐ jī jǐ jī gān yóu', 'synthetic', 'Synthetic preservative booster.'],
    ['月桂酸', 'ok', 'lauric acid', 'yuè guì suān', 'plant', 'Coconut or palm kernel oil.'],
    ['乳酸', 'ok', 'lactic acid', 'rǔ suān', 'synthetic', 'Made by fermentation of sugar; not from milk.'],
    ['乳酸钠', 'ok', 'sodium lactate', 'rǔ suān nà', 'synthetic', 'Fermentation-derived.'],
    ['乳酸菌发酵产物滤液', 'ok', 'lactobacillus ferment filtrate', 'rǔ suān jūn fā jiào chǎn wù lǜ yè', 'synthetic', 'Bacterial ferment.'],
    ['大豆卵磷脂', 'ok', 'soy lecithin', 'dà dòu luǎn lín zhī', 'plant', 'Plant.'],
    ['向日葵卵磷脂', 'ok', 'sunflower lecithin', 'xiàng rì kuí luǎn lín zhī', 'plant', 'Plant.'],
    ['植物角鲨烷', 'ok', 'plant squalane', 'zhí wù jiǎo shā wán', 'plant', 'Stated plant source.'],
    ['橄榄角鲨烷', 'ok', 'olive squalane', 'gǎn lǎn jiǎo shā wán', 'plant', 'Olive-derived.'],
    ['甘蔗角鲨烷', 'ok', 'sugarcane squalane', 'gān zhè jiǎo shā wán', 'plant', 'Fermented sugarcane.'],
    ['重组胶原蛋白', 'ok', 'recombinant collagen', 'chóng zǔ jiāo yuán dàn bái', 'synthetic', 'Made by microbial fermentation.'],
    ['人源化胶原蛋白', 'ok', 'humanised collagen (recombinant)', 'rén yuán huà jiāo yuán dàn bái', 'synthetic', 'Recombinant, made by fermentation; also covers 重组III型人源化胶原蛋白.'],
    ['重组III型胶原蛋白', 'ok', 'recombinant type III collagen', 'chóng zǔ sān xíng jiāo yuán dàn bái', 'synthetic', 'Made by microbial fermentation.'],
    ['重组Ⅲ型胶原蛋白', 'ok', 'recombinant type III collagen', 'chóng zǔ sān xíng jiāo yuán dàn bái', 'synthetic', 'Made by microbial fermentation.'],
    ['重组人胶原蛋白', 'ok', 'recombinant human collagen', 'chóng zǔ rén jiāo yuán dàn bái', 'synthetic', 'Made by microbial fermentation; no human tissue.'],
    ['合成蜂蜡', 'ok', 'synthetic beeswax', 'hé chéng fēng là', 'synthetic', 'Synthetic esters; no bee material.'],
    ['植物角蛋白', 'ok', 'plant keratin (marketing name)', 'zhí wù jiǎo dàn bái', 'plant', 'Plant protein sold under a keratin name.'],
    ['重组人源化胶原蛋白', 'ok', 'recombinant humanised collagen', 'chóng zǔ rén yuán huà jiāo yuán dàn bái', 'synthetic', 'Made by microbial fermentation; no human tissue.'],
    ['类人胶原蛋白', 'ok', 'human-like collagen (recombinant)', 'lèi rén jiāo yuán dàn bái', 'synthetic', 'Recombinant, made by fermentation.'],
    ['寡肽-1', 'ok', 'sh-oligopeptide-1 (EGF)', 'guǎ tài-1', 'synthetic', 'Recombinant.'],
    ['蛇毒肽', 'ok', 'snake-venom-like peptide', 'shé dú tài', 'synthetic', 'Synthetic dipeptide; no snake material.'],
    ['合成麝香', 'ok', 'synthetic musk', 'hé chéng shè xiāng', 'synthetic', 'Synthetic.'],
    ['人工麝香', 'ok', 'artificial musk', 'rén gōng shè xiāng', 'synthetic', 'Synthetic.'],
    ['降龙涎香醚', 'ok', 'ambrox', 'jiàng lóng xián xiāng mí', 'synthetic', 'Synthetic ambergris substitute.'],
    ['人造珍珠', 'ok', 'artificial pearl', 'rén zào zhēn zhū', 'synthetic', 'Synthetic.'],
    ['珍珠岩', 'ok', 'perlite', 'zhēn zhū yán', 'mineral', 'Volcanic mineral.'],
    ['珠光粉', 'ok', 'pearlescent pigment', 'zhū guāng fěn', 'mineral', 'Usually mica coated with titanium dioxide.'],
    ['羊脂玉', 'ok', 'mutton-fat jade', 'yáng zhī yù', 'mineral', 'A jade name, not fat.'],
    ['胭脂红', 'ok', 'Ponceau 4R (CI 16255)', 'yān zhī hóng', 'synthetic', 'Synthetic dye; insect carmine is 胭脂虫红 / CI 75470.'],
    ['牛磺酸', 'ok', 'taurine', 'niú huáng suān', 'synthetic', 'Commercial taurine is synthetic.'],
    ['尿素', 'ok', 'urea', 'niào sù', 'synthetic', 'Synthetic.'],
    ['人造丝', 'ok', 'rayon', 'rén zào sī', 'synthetic', 'Regenerated cellulose, not silk.'],
    ['天丝', 'ok', 'lyocell (Tencel)', 'tiān sī', 'plant', 'Wood-pulp fibre, not silk.'],
    ['山梨醇', 'ok', 'sorbitol', 'shān lí chún', 'plant', 'Sugar alcohol from glucose.'],
    ['木糖醇', 'ok', 'xylitol', 'mù táng chún', 'plant', 'Sugar alcohol from plants.'],
    ['牛油果', 'ok', 'avocado', 'niú yóu guǒ', 'plant', 'Avocado fruit and oil; not beef fat.'],
    ['鳄梨', 'ok', 'avocado (INCI)', 'è lí', 'plant', 'Avocado; Persea gratissima.'],
    ['牛油果树', 'ok', 'shea tree (INCI)', 'niú yóu guǒ shù', 'plant', 'Butyrospermum parkii (shea).'],
    ['牛油树', 'ok', 'shea tree', 'niú yóu shù', 'plant', 'Shea.'],
    ['乳木果', 'ok', 'shea', 'rǔ mù guǒ', 'plant', 'Shea butter; plant.'],
    ['乳油木', 'ok', 'shea', 'rǔ yóu mù', 'plant', 'Shea; plant.'],
    ['乳香', 'ok', 'frankincense', 'rǔ xiāng', 'plant', 'Boswellia resin.'],
    ['牛蒡', 'ok', 'burdock', 'niú bàng', 'plant', 'Plant.'],
    ['牛膝', 'ok', 'achyranthes root', 'niú xī', 'plant', 'Herb.'],
    ['牛至', 'ok', 'oregano', 'niú zhì', 'plant', 'Herb.'],
    ['猪苓', 'ok', 'polyporus mushroom', 'zhū líng', 'plant', 'Fungus; no pig.'],
    ['猪笼草', 'ok', 'pitcher plant', 'zhū lóng cǎo', 'plant', 'Nepenthes; plant.'],
    ['猪毛菜', 'ok', 'saltwort', 'zhū máo cài', 'plant', 'Salsola; plant.'],
    ['猪殃殃', 'ok', 'cleavers', 'zhū yāng yāng', 'plant', 'Galium; plant.'],
    ['猪牙皂', 'ok', 'gleditsia pod', 'zhū yá zào', 'plant', 'Soap-pod herb used in traditional shampoos; no pig.'],
    ['猪鬃草', 'ok', 'maidenhair fern', 'zhū zōng cǎo', 'plant', 'Adiantum fern; no pig.'],
    ['小猪佩奇', 'ok', 'Peppa Pig (licensed character)', 'xiǎo zhū pèi qí', 'synthetic', 'Cartoon name on children\'s products, not an ingredient.'],
    ['粉红猪小妹', 'ok', 'Peppa Pig (licensed character)', 'fěn hóng zhū xiǎo mèi', 'synthetic', 'Cartoon name, not an ingredient.'],
    ['猪猪侠', 'ok', 'GG Bond (cartoon character)', 'zhū zhū xiá', 'synthetic', 'Cartoon name on children\'s products, not an ingredient.'],
    ['猪年', 'ok', 'Year of the Pig', 'zhū nián', 'synthetic', 'Zodiac edition name, not an ingredient.'],
    ['鱼尾葵', 'ok', 'fishtail palm', 'yú wěi kuí', 'plant', 'Plant.'],
    ['鱼子兰', 'ok', 'chloranthus', 'yú zǐ lán', 'plant', 'Plant.'],
    ['贝母', 'ok', 'fritillaria bulb', 'bèi mǔ', 'plant', 'Herb (川贝母, 浙贝母); not shellfish.'],
    ['川贝', 'ok', 'fritillaria bulb', 'chuān bèi', 'plant', 'Herb; not shellfish.'],
    ['浙贝', 'ok', 'fritillaria bulb', 'zhè bèi', 'plant', 'Herb; not shellfish.'],
    ['贝亲', 'ok', 'Pigeon (brand)', 'bèi qīn', 'synthetic', 'Baby-care brand name, not shellfish.'],
    ['宝贝', 'ok', 'baby (word)', 'bǎo bèi', 'synthetic', 'Word for baby, not shellfish.'],
    ['羊栖菜', 'ok', 'hijiki seaweed', 'yáng qī cài', 'plant', 'Seaweed.'],
    ['羊肚菌', 'ok', 'morel mushroom', 'yáng dù jūn', 'plant', 'Fungus.'],
    ['淫羊藿', 'ok', 'epimedium', 'yín yáng huò', 'plant', 'Herb.'],
    ['马齿苋', 'ok', 'purslane', 'mǎ chǐ xiàn', 'plant', 'Plant; common in soothing products.'],
    ['马鞭草', 'ok', 'verbena', 'mǎ biān cǎo', 'plant', 'Plant.'],
    ['马栗', 'ok', 'horse chestnut', 'mǎ lì', 'plant', 'Plant.'],
    ['鹿角菜', 'ok', 'Gloiopeltis seaweed', 'lù jiǎo cài', 'plant', 'Red seaweed.'],
    ['鹿角菜胶', 'ok', 'carrageenan', 'lù jiǎo cài jiāo', 'plant', 'Seaweed gum.'],
    ['鸡冠花', 'ok', 'cockscomb flower', 'jī guān huā', 'plant', 'Celosia; plant.'],
    ['鸡蛋花', 'ok', 'frangipani', 'jī dàn huā', 'plant', 'Plumeria flower.'],
    ['鸡血藤', 'ok', 'spatholobus vine', 'jī xuè téng', 'plant', 'Herb.'],
    ['雪燕', 'ok', 'sterculia gum', 'xuě yàn', 'plant', 'Plant gum sold as snow bird nest; not bird.'],
    ['燕麦', 'ok', 'oat', 'yàn mài', 'plant', 'Plant.'],
    ['鱼腥草', 'ok', 'houttuynia', 'yú xīng cǎo', 'plant', 'Herb.'],
    ['金鱼草', 'ok', 'snapdragon', 'jīn yú cǎo', 'plant', 'Flower.'],
    ['熊果', 'ok', 'bearberry', 'xióng guǒ', 'plant', 'Plant.'],
    ['熊果苷', 'ok', 'arbutin', 'xióng guǒ gān', 'plant', 'Plant or synthetic.'],
    ['蛇床子', 'ok', 'cnidium fruit', 'shé chuáng zǐ', 'plant', 'Herb.'],
    ['虎杖', 'ok', 'giant knotweed', 'hǔ zhàng', 'plant', 'Polygonum cuspidatum.'],
    ['虎耳草', 'ok', 'saxifrage', 'hǔ ěr cǎo', 'plant', 'Plant.'],
    ['龙眼', 'ok', 'longan', 'lóng yǎn', 'plant', 'Fruit.'],
    ['龙胆', 'ok', 'gentian', 'lóng dǎn', 'plant', 'Herb.'],
    ['龙血树', 'ok', 'dragon tree', 'lóng xuè shù', 'plant', 'Dracaena resin.'],
    ['蜂斗菜', 'ok', 'butterbur', 'fēng dǒu cài', 'plant', 'Petasites; plant.'],
    ['椰油酸', 'ok', 'coconut acid', 'yē yóu suān', 'plant', 'Coconut fatty acids (e.g. 椰油酸钠 sodium cocoate); not 油酸 of unstated source.'],
    ['橄榄油酸', 'ok', 'olive fatty acids', 'gǎn lǎn yóu suān', 'plant', 'Olive-derived (e.g. 山梨坦橄榄油酸酯).'],
    ['棕榈仁油酸', 'ok', 'palm kernel acid', 'zōng lǘ rén yóu suān', 'plant', 'Palm kernel fatty acids.'],
    ['蓖麻油酸', 'ok', 'ricinoleic acid', 'bì má yóu suān', 'plant', 'Castor oil fatty acid.'],
    ['亚油酸', 'ok', 'linoleic acid', 'yà yóu suān', 'plant', 'Plant oil fatty acid.'],
    ['香精', 'ok', 'fragrance', 'xiāng jīng', 'synthetic', 'Fragrance blend; animal musk or ambergris, if used, is named separately.'],
    ['香料', 'ok', 'fragrance / perfume', 'xiāng liào', 'synthetic', 'Fragrance blend.']
  ],
  products: [
    ['湿巾|湿纸巾|婴儿湿巾|手口湿巾', 'clean', 'wet wipes', 'water, nonwoven cloth, preservative, fragrance, plant extracts', 'Usually no animal material; alcohol is acceptable.'],
    ['消毒湿巾|酒精湿巾|酒精棉片|消毒棉片', 'clean', 'disinfecting / alcohol wipes', 'ethanol or quaternary ammonium, water, nonwoven cloth', 'Alcohol is acceptable; no animal material expected.'],
    ['纸巾|面巾纸|抽纸|卫生纸|手帕纸|厨房纸', 'clean', 'tissue paper', 'wood pulp', 'Plain paper; no animal material.'],
    ['乳霜纸|保湿纸巾|云柔巾', 'caution', 'lotion tissues', 'wood pulp, glycerin, sorbitol, sometimes squalane', 'Glycerin and squalane can be animal-sourced; check the list.'],
    ['卫生巾|护垫|纸尿裤|尿裤|拉拉裤', 'clean', 'sanitary pads / diapers', 'pulp, nonwoven fabric, superabsorbent polymer, film', 'Synthetic; no animal material expected.'],
    ['化妆棉|棉签|卸妆棉', 'clean', 'cotton pads / swabs', 'cotton or viscose', 'Plant fibre.'],
    ['免洗洗手液|洗手凝胶|速干手消毒', 'caution', 'hand sanitiser', 'ethanol, water, carbomer, glycerin', 'Alcohol is acceptable; glycerin source is usually plant or synthetic but unstated.'],
    ['消毒液|84消毒液|含氯消毒', 'clean', 'disinfectant', 'sodium hypochlorite or quats, water', 'Synthetic.'],
    ['洗洁精|餐具洗涤剂', 'clean', 'dishwashing liquid', 'synthetic surfactants, water, fragrance', 'Usually synthetic; soap-based types can use tallow.'],
    ['洗衣液|洗衣粉|洗衣凝珠', 'clean', 'laundry detergent', 'synthetic surfactants, builders, enzymes, fragrance', 'Usually synthetic.'],
    ['柔顺剂|衣物护理剂', 'caution', 'fabric softener', 'esterquat or tallow-derived quaternary ammonium, fragrance', 'Softener quats are often made from tallow (牛脂基); check the list.'],
    ['香皂|肥皂|洗衣皂|手工皂', 'caution', 'bar soap', 'soap base (sodium tallowate or sodium palmate/cocoate), glycerin, fragrance', 'Tallow soap is common; lard in some handmade soap. Check for 牛脂/猪油/皂基.'],
    ['洗手液', 'caution', 'liquid hand wash', 'surfactants, glycerin, fragrance, sometimes milk or honey', 'Check for glycerin source and milk/honey variants.'],
    ['沐浴露|沐浴乳', 'caution', 'shower gel', 'surfactants, glycerin, fragrance, sometimes milk, honey or soap base', 'Check for milk, honey, soap base and glycerin.'],
    ['洗发水|洗发露', 'caution', 'shampoo', 'surfactants, glycerin, panthenol, sometimes keratin or silk protein', 'Keratin and silk proteins are animal-derived.'],
    ['护发素|发膜', 'caution', 'conditioner / hair mask', 'cetearyl alcohol, quats, keratin, collagen, silk proteins', 'Protein hydrolysates are often animal-derived.'],
    ['牙膏', 'caution', 'toothpaste', 'abrasive, sorbitol, glycerin, sometimes propolis or pearl powder', 'Glycerin source unstated; propolis and pearl are animal.'],
    ['漱口水', 'clean', 'mouthwash', 'water, ethanol or none, sorbitol, flavour, cetylpyridinium chloride', 'Alcohol is acceptable; usually no animal material.'],
    ['牙刷', 'caution', 'toothbrush', 'plastic handle, nylon bristles', 'Nylon is fine; boar-bristle (猪鬃) brushes are pig.'],
    ['洗面奶|洁面乳|洁面膏', 'caution', 'facial cleanser', 'stearic and myristic acids, potassium hydroxide, glycerin', 'Fatty acids and glycerin can be animal-sourced.'],
    ['爽肤水|化妆水', 'caution', 'toner', 'water, glycerin, butylene glycol, hyaluronic acid', 'Glycerin and hyaluronic acid sources are unstated.'],
    ['乳液|面霜|身体乳|护手霜|润肤霜', 'caution', 'lotion / cream', 'water, oils, glycerin, fatty alcohols, stearates, squalane', 'Many unstated-source fats; lanolin common in hand cream.'],
    ['精华液|精华|原液', 'caution', 'serum', 'water, glycerin, hyaluronic acid, peptides, collagen', 'Collagen and hyaluronic acid sources unstated.'],
    ['面膜', 'caution', 'sheet mask', 'water, glycerin, hyaluronic acid, collagen, silk or nonwoven sheet', 'Collagen, silk and snail variants are animal.'],
    ['眼霜', 'caution', 'eye cream', 'oils, glycerin, peptides, ceramides', 'Unstated-source fats and peptides.'],
    ['防晒霜|防晒乳|隔离霜', 'caution', 'sunscreen', 'UV filters, glycerin, fatty alcohols, stearates', 'Unstated-source fats.'],
    ['口红|唇膏|唇釉|润唇膏', 'animal', 'lipstick / lip balm', 'beeswax, lanolin, oils, pigments incl. carmine', 'Beeswax, lanolin and carmine are very common.'],
    ['睫毛膏', 'caution', 'mascara', 'waxes (beeswax, carnauba), pigments, shellac', 'Beeswax and shellac are common.'],
    ['粉底|粉饼|散粉|气垫|BB霜', 'caution', 'foundation / powder', 'pigments, talc, magnesium stearate, squalane, glycerin', 'Stearates and squalane sources unstated.'],
    ['腮红|眼影|高光', 'caution', 'blush / eyeshadow', 'talc, mica, stearates, pigments, sometimes carmine', 'Reds may use carmine; stearates unstated.'],
    ['指甲油', 'caution', 'nail polish', 'nitrocellulose, solvents, resins, pigments', 'Pearl shades may use guanine from fish scales.'],
    ['香水|淡香水|古龙水', 'clean', 'perfume', 'alcohol, fragrance, water', 'Alcohol is acceptable; musk and ambergris are almost always synthetic.'],
    ['花露水|驱蚊液|驱蚊水', 'clean', 'toilet water / insect repellent', 'alcohol, water, fragrance, DEET or IR3535', 'Alcohol is acceptable.'],
    ['发胶|定型喷雾|啫喱水', 'clean', 'hair styling', 'alcohol, polymers, propellant', 'Synthetic.'],
    ['染发剂|染发膏', 'caution', 'hair dye', 'dye precursors, fatty alcohols, ammonia', 'Fatty alcohols and conditioners may be animal-sourced.'],
    ['剃须膏|剃须泡沫', 'caution', 'shaving cream', 'stearic acid, triethanolamine, glycerin', 'Stearic acid source unstated.'],
    ['卸妆油|卸妆水|卸妆膏', 'caution', 'makeup remover', 'oils, emulsifiers, glycerin', 'Check oil and emulsifier sources.'],
    ['护臀膏', 'caution', 'nappy cream', 'zinc oxide, lanolin, petrolatum', 'Lanolin is common.'],
    ['凡士林', 'clean', 'petroleum jelly', 'petrolatum', 'Mineral.'],
    ['马油|马油霜', 'animal', 'horse oil cream', 'horse fat', 'Horse-derived.'],
    ['绵羊油|羊毛脂霜', 'animal', 'sheep oil / lanolin cream', 'lanolin', 'Sheep-derived.'],
    ['蜗牛霜|蜗牛原液', 'animal', 'snail cream', 'snail secretion filtrate', 'Snail-derived.'],
    ['珍珠霜|珍珠膏', 'animal', 'pearl cream', 'pearl powder', 'Mollusc-derived.'],
    ['胎盘素|羊胎素', 'animal', 'placenta products', 'placenta extract', 'Animal placenta; species often unstated.'],
    ['猪油膏|猪油皂', 'haram', 'lard balm / lard soap', 'lard', 'Pig fat.'],
    ['猪鬃刷|猪鬃梳', 'haram', 'boar-bristle brush', 'pig bristle', 'Pig hair.']
  ]
};
