/* HalalCheck knowledge base — part 2: safe ingredients (status ok / note).
 * These power the English gloss of the ingredient list and protect compounds such as 肉桂 or 鸡蛋 from the generic 肉/鸡 rules.
 * Shape: [term, status, english, pinyin, category, note]  — pinyin optional for ok entries.
 */
(function (DB) {
  var ok = function (t, en, c, n) { return [t, 'ok', en, '', c || 'plant', n || '']; };
  var note = function (t, en, c, n) { return [t, 'note', en, '', c || 'misc', n || '']; };
  DB.entries.push(
    // ---------- compounds that contain 肉/鸡/牛/羊/鸭/血/酒/骨/胶 but are fine
    ok('肉桂', 'cinnamon', 'spice'), ok('肉桂粉', 'cinnamon powder', 'spice'), ok('肉桂皮', 'cinnamon bark', 'spice'),
    ok('肉豆蔻', 'nutmeg', 'spice'), ok('肉蔻', 'nutmeg', 'spice'), ok('肉豆蔻衣', 'mace', 'spice'), ok('肉苁蓉', 'cistanche (herb)', 'herb'),
    ok('左旋肉碱', 'L-carnitine (synthetic)', 'additive'), ok('L-肉碱', 'L-carnitine', 'additive'), ok('肉碱', 'carnitine (synthetic)', 'additive'),
    ok('果肉', 'fruit pulp', 'fruit'), ok('果肉含量', 'fruit content', 'label'), ok('椰肉', 'coconut flesh', 'fruit'), ok('桂圆肉', 'dried longan', 'fruit'),
    ok('龙眼肉', 'dried longan', 'fruit'), ok('枣肉', 'date flesh', 'fruit'), ok('红枣肉', 'red date flesh', 'fruit'), ok('山楂肉', 'hawthorn pulp', 'fruit'),
    ok('荔枝肉', 'lychee flesh', 'fruit'), ok('芒果肉', 'mango pulp', 'fruit'), ok('瓜肉', 'melon flesh', 'fruit'), ok('杏肉', 'apricot flesh', 'fruit'),
    ok('桃肉', 'peach flesh', 'fruit'), ok('莓果肉', 'berry pulp', 'fruit'), ok('肉质', 'texture (flesh-like)', 'label'), ok('多肉', 'pulpy', 'label'),
    ok('鱼肉', 'fish meat', 'seafood'), ok('鳗鱼肉', 'eel meat', 'seafood'), ok('面筋', 'wheat gluten', 'grain'), ok('辣条', 'spicy gluten strips', 'snack'),
    ok('鸡蛋', 'egg', 'egg'), ok('鸡蛋粉', 'egg powder', 'egg'), ok('鸡蛋液', 'liquid egg', 'egg'), ok('鸡蛋黄', 'egg yolk', 'egg'), ok('鸡蛋白', 'egg white', 'egg'),
    ok('鸡蛋仔', 'egg waffle', 'snack'), ok('鸡枞', 'termite mushroom', 'fungus'), ok('鸡枞菌', 'termite mushroom', 'fungus'), ok('鸡腿菇', 'shaggy mane mushroom', 'fungus'),
    ok('鸡毛菜', 'baby bok choy', 'vegetable'), ok('鸡头米', 'fox nut (euryale)', 'plant'), ok('鸡骨草', 'abrus herb', 'herb'), ok('鸡血藤', 'spatholobus herb', 'herb'),
    ok('鸡屎藤', 'paederia herb', 'herb'), ok('鸡心果', 'mini apple', 'fruit'), ok('鸡油菌', 'chanterelle mushroom', 'fungus'),
    ok('牛奶', 'milk', 'dairy'), ok('牛乳', 'milk', 'dairy'), ok('生牛乳', 'raw milk', 'dairy'), ok('生牛奶', 'raw milk', 'dairy'), ok('牛乳粉', 'milk powder', 'dairy'),
    ok('牛奶粉', 'milk powder', 'dairy'), ok('牛初乳', 'bovine colostrum', 'dairy'), ok('牛油果', 'avocado', 'fruit'), ok('牛油果油', 'avocado oil', 'oil'),
    ok('牛磺酸', 'taurine (synthetic)', 'additive'), ok('牛蒡', 'burdock root', 'vegetable'), ok('牛至', 'oregano', 'spice'), ok('牛至叶', 'oregano leaf', 'spice'),
    ok('牛膝', 'achyranthes root (herb)', 'herb'), ok('牛大力', 'millettia root (herb)', 'herb'), ok('牛奶巧克力', 'milk chocolate', 'sweet'),
    ok('牛轧糖', 'nougat', 'sweet', 'Check separately for 明胶.'), ok('牛角包', 'croissant', 'bakery'), ok('牛皮糖', 'chewy candy (name only)', 'sweet'),
    ok('牛油曲奇', 'butter cookie (Hong Kong usage)', 'bakery'), ok('牦牛奶', 'yak milk', 'dairy'), ok('牦牛乳', 'yak milk', 'dairy'),
    ok('羊奶', 'goat milk', 'dairy'), ok('羊乳', 'goat milk', 'dairy'), ok('羊奶粉', 'goat milk powder', 'dairy'), ok('羊乳粉', 'goat milk powder', 'dairy'),
    ok('羊角豆', 'okra', 'vegetable'), ok('羊栖菜', 'hijiki seaweed', 'seaweed'), ok('羊肚菌', 'morel mushroom', 'fungus'),
    ok('鸭蛋', 'duck egg', 'egg'), ok('鸭蛋黄', 'duck egg yolk', 'egg'), ok('咸鸭蛋', 'salted duck egg', 'egg'), ok('鸭梨', 'Ya pear', 'fruit'), ok('鸭儿芹', 'mitsuba herb', 'herb'),
    ok('鹅蛋', 'goose egg', 'egg'), ok('鸽蛋', 'pigeon egg', 'egg'), ok('鹌鹑蛋', 'quail egg', 'egg'), ok('鸵鸟蛋', 'ostrich egg', 'egg'),
    ok('驼奶', 'camel milk', 'dairy'), ok('驼乳', 'camel milk', 'dairy'), ok('驼奶粉', 'camel milk powder', 'dairy'),
    ok('血糯米', 'black glutinous rice', 'grain'), ok('血糯', 'black glutinous rice', 'grain'), ok('血橙', 'blood orange', 'fruit'), ok('补血', 'blood-nourishing (claim)', 'label'),
    ok('血糖', 'blood sugar (label text)', 'label'), ok('血藤', 'spatholobus herb', 'herb'),
    ok('酒石酸', 'tartaric acid (not alcohol)', 'additive'), ok('酒石酸氢钾', 'potassium bitartrate', 'additive'), ok('酒石酸钠', 'sodium tartrate', 'additive'),
    ok('酒石酸钾钠', 'potassium sodium tartrate', 'additive'), ok('酒店', 'hotel (address text)', 'label'), ok('啤酒花', 'hops (plant)', 'plant'),
    ok('啤酒酵母', 'brewer\'s yeast', 'additive'), ok('酵母', 'yeast', 'additive'), ok('酵母粉', 'yeast powder', 'additive'), ok('酵母提取物', 'yeast extract', 'additive'),
    ok('酵母抽提物', 'yeast extract', 'additive'), ok('酵母β-葡聚糖', 'yeast beta-glucan', 'additive'), ok('酿造', 'brewed / fermented', 'label'), ok('发酵', 'fermented', 'label'),
    note('酱油', 'soy sauce', 'condiment', 'Naturally fermented; trace ethanol from fermentation only. Widely accepted as halal. Some brands add 食用酒精 — it would be listed.'),
    note('酿造酱油', 'brewed soy sauce', 'condiment', 'See 酱油.'), note('生抽', 'light soy sauce', 'condiment', 'See 酱油.'), note('老抽', 'dark soy sauce', 'condiment', 'See 酱油.'),
    ok('醋', 'vinegar', 'condiment'), ok('陈醋', 'aged vinegar', 'condiment'), ok('米醋', 'rice vinegar', 'condiment'), ok('白醋', 'white vinegar', 'condiment'),
    ok('香醋', 'black vinegar', 'condiment'), ok('果醋', 'fruit vinegar', 'condiment'), ok('苹果醋', 'apple cider vinegar', 'condiment'), ok('醋精', 'vinegar essence', 'condiment'),
    ok('乙酸', 'acetic acid', 'additive'), ok('乙酸钠', 'sodium acetate', 'additive'), ok('乙酸乙酯', 'ethyl acetate (flavour solvent)', 'additive'), ok('乙基麦芽酚', 'ethyl maltol', 'additive'),
    ok('乙酰磺胺酸钾', 'acesulfame potassium', 'sweetener'), ok('乙基香兰素', 'ethyl vanillin', 'additive'), ok('香兰素', 'vanillin', 'additive'), ok('香草荚', 'vanilla pod', 'spice'),
    ok('鱼骨粉', 'fish bone powder', 'seafood'), ok('鱼骨', 'fish bone', 'seafood'), ok('软骨', 'cartilage', 'meat'),
    ok('果胶', 'pectin', 'thickener'), ok('卡拉胶', 'carrageenan', 'thickener'), ok('黄原胶', 'xanthan gum', 'thickener'), ok('瓜尔胶', 'guar gum', 'thickener'),
    ok('阿拉伯胶', 'gum arabic', 'thickener'), ok('结冷胶', 'gellan gum', 'thickener'), ok('刺槐豆胶', 'locust bean gum', 'thickener'), ok('槐豆胶', 'locust bean gum', 'thickener'),
    ok('魔芋胶', 'konjac gum', 'thickener'), ok('海藻胶', 'alginate', 'thickener'), ok('琼胶', 'agar', 'thickener'), ok('亚麻籽胶', 'flaxseed gum', 'thickener'),
    ok('田菁胶', 'sesbania gum', 'thickener'), ok('沙蒿胶', 'artemisia gum', 'thickener'), ok('塔拉胶', 'tara gum', 'thickener'), ok('可得然胶', 'curdlan', 'thickener'),
    ok('罗望子胶', 'tamarind gum', 'thickener'), ok('罗望子多糖胶', 'tamarind polysaccharide', 'thickener'), ok('决明胶', 'cassia gum', 'thickener'), ok('桃胶', 'peach gum', 'plant'),
    ok('皂角米', 'honey locust seed', 'plant'), ok('雪燕', 'tragacanth-like plant gum', 'plant'), ok('黄蓍胶', 'tragacanth', 'thickener'), ok('微晶纤维素', 'microcrystalline cellulose', 'thickener'),
    ok('羧甲基纤维素钠', 'sodium CMC', 'thickener'), ok('甲基纤维素', 'methyl cellulose', 'thickener'), ok('羟丙基甲基纤维素', 'HPMC', 'thickener'), ok('纤维素', 'cellulose', 'thickener'),
    ok('海藻酸钠', 'sodium alginate', 'thickener'), ok('海藻酸丙二醇酯', 'propylene glycol alginate', 'thickener'), ok('普鲁兰多糖', 'pullulan', 'thickener'),
    ok('透明质酸', 'hyaluronic acid (fermentation)', 'additive'), ok('透明质酸钠', 'sodium hyaluronate', 'additive'), ok('燕窝', 'bird\'s nest', 'animal'), ok('燕窝酸', 'sialic acid', 'additive'),
    // ---------- fats and oils (plant)
    ok('植物油', 'vegetable oil', 'oil'), ok('食用植物油', 'edible vegetable oil', 'oil'), ok('精炼植物油', 'refined vegetable oil', 'oil'), ok('植物油脂', 'vegetable fat', 'oil'),
    ok('氢化植物油', 'hydrogenated vegetable oil', 'oil'), ok('部分氢化植物油', 'partially hydrogenated vegetable oil', 'oil'), ok('棕榈油', 'palm oil', 'oil'),
    ok('精炼棕榈油', 'refined palm oil', 'oil'), ok('棕榈仁油', 'palm kernel oil', 'oil'), ok('棕榈硬脂', 'palm stearin', 'oil'), ok('棕榈液油', 'palm olein', 'oil'),
    ok('大豆油', 'soybean oil', 'oil'), ok('菜籽油', 'rapeseed oil', 'oil'), ok('菜油', 'rapeseed oil', 'oil'), ok('花生油', 'peanut oil', 'oil'), ok('玉米油', 'corn oil', 'oil'),
    ok('葵花籽油', 'sunflower oil', 'oil'), ok('葵花油', 'sunflower oil', 'oil'), ok('芝麻油', 'sesame oil', 'oil'), ok('香油', 'sesame oil', 'oil'), ok('橄榄油', 'olive oil', 'oil'),
    ok('椰子油', 'coconut oil', 'oil'), ok('米糠油', 'rice bran oil', 'oil'), ok('稻米油', 'rice oil', 'oil'), ok('茶籽油', 'tea seed oil', 'oil'), ok('山茶油', 'camellia oil', 'oil'),
    ok('亚麻籽油', 'flaxseed oil', 'oil'), ok('核桃油', 'walnut oil', 'oil'), ok('芥花油', 'canola oil', 'oil'), ok('芥花籽油', 'canola oil', 'oil'), ok('调和油', 'blended vegetable oil', 'oil'),
    ok('食用调和油', 'blended vegetable oil', 'oil'), ok('色拉油', 'salad oil', 'oil'), ok('植物起酥油', 'vegetable shortening', 'oil'), ok('植物酥油', 'vegetable shortening', 'oil'),
    ok('代可可脂', 'cocoa butter substitute', 'oil'), ok('可可脂', 'cocoa butter', 'oil'), ok('可可液块', 'cocoa mass', 'cocoa'), ok('可可粉', 'cocoa powder', 'cocoa'),
    ok('可可块', 'cocoa mass', 'cocoa'), ok('可可', 'cocoa', 'cocoa'), ok('黄油', 'butter', 'dairy'), ok('奶油', 'cream / butter', 'dairy'), ok('稀奶油', 'cream', 'dairy'),
    ok('淡奶油', 'whipping cream', 'dairy'), ok('无水奶油', 'anhydrous butter', 'dairy'), ok('乳脂', 'milk fat', 'dairy'), ok('乳脂肪', 'milk fat', 'dairy'), ok('植脂末', 'non-dairy creamer', 'dairy'),
    ok('奶精', 'creamer', 'dairy'), ok('植物奶油', 'non-dairy whipped topping', 'dairy'), ok('植脂奶油', 'non-dairy cream', 'dairy'), ok('中链甘油三酯', 'MCT oil (coconut)', 'oil'),
    ok('MCT', 'MCT oil', 'oil'), ok('磷脂', 'phospholipid (lecithin)', 'additive'), ok('大豆磷脂', 'soy lecithin', 'additive'), ok('卵磷脂', 'lecithin', 'additive'),
    ok('蛋黄卵磷脂', 'egg lecithin', 'additive'), ok('改性大豆磷脂', 'modified soy lecithin', 'additive'), ok('酶解大豆磷脂', 'enzymatically modified soy lecithin', 'additive'),
    ok('鱼油', 'fish oil', 'seafood'), ok('深海鱼油', 'deep-sea fish oil', 'seafood'), ok('鱼肝油', 'cod liver oil', 'seafood'), ok('藻油', 'algal oil', 'oil'), ok('DHA藻油', 'DHA algal oil', 'oil'),
    ok('DHA', 'DHA', 'additive'), ok('ARA', 'ARA', 'additive'), ok('花生四烯酸', 'arachidonic acid', 'additive'), ok('二十二碳六烯酸', 'DHA', 'additive'),
    ok('结构脂', 'structured lipid (OPO, palm-based)', 'oil'), ok('OPO', 'OPO structured lipid', 'oil'), ok('氢化松香甘油酯', 'glycerol ester of hydrogenated rosin', 'additive'),
    ok('松香甘油酯', 'glycerol ester of rosin', 'additive'), ['三乙酸甘油酯', 'caution', 'triacetin (E1518; glycerol source unverifiable)', 'sān yǐ suān gān yóu zhǐ', 'additive', 'Glycerol may be animal- or plant-derived.'], ['棕榈酸', 'caution', 'palmitic acid (palm or animal fat — unverifiable)', 'zōng lǘ suān', 'additive', ''],
    // ---------- dairy (fine)
    ok('全脂奶粉', 'whole milk powder', 'dairy'), ok('脱脂奶粉', 'skimmed milk powder', 'dairy'), ok('乳粉', 'milk powder', 'dairy'), ok('全脂乳粉', 'whole milk powder', 'dairy'),
    ok('脱脂乳粉', 'skimmed milk powder', 'dairy'), ok('奶粉', 'milk powder', 'dairy'), ok('复原乳', 'reconstituted milk', 'dairy'), ok('炼乳', 'condensed milk', 'dairy'),
    ok('甜炼乳', 'sweetened condensed milk', 'dairy'), ok('淡奶', 'evaporated milk', 'dairy'), ok('乳糖', 'lactose', 'dairy'), ok('乳酸', 'lactic acid', 'additive'),
    ok('乳酸钙', 'calcium lactate', 'additive'), ok('乳酸钠', 'sodium lactate', 'additive'), ok('乳酸菌', 'lactic acid bacteria', 'additive'), ok('乳酸链球菌素', 'nisin', 'additive'),
    ok('乳铁蛋白', 'lactoferrin', 'dairy'), ok('乳矿物盐', 'milk minerals', 'dairy'), ok('乳钙', 'milk calcium', 'dairy'), ok('酸奶', 'yoghurt', 'dairy', 'Check separately for 明胶.'),
    ok('酸奶粉', 'yoghurt powder', 'dairy'), ok('发酵乳', 'fermented milk', 'dairy'), ok('益生菌', 'probiotics', 'additive'), ok('双歧杆菌', 'bifidobacterium', 'additive'),
    ok('嗜酸乳杆菌', 'lactobacillus acidophilus', 'additive'), ok('保加利亚乳杆菌', 'lactobacillus bulgaricus', 'additive'), ok('嗜热链球菌', 'streptococcus thermophilus', 'additive'), ok('唾液链球菌嗜热亚种', 'Streptococcus thermophilus (yogurt culture)', 'additive'), ok('德氏乳杆菌保加利亚亚种', 'Lactobacillus bulgaricus (yogurt culture)', 'additive'), ok('动物双歧杆菌乳亚种', 'Bifidobacterium lactis (probiotic)', 'additive'), ok('乳双歧杆菌', 'Bifidobacterium lactis', 'additive'), ok('鼠李糖乳杆菌', 'Lactobacillus rhamnosus', 'additive'), ok('副干酪乳杆菌', 'Lactobacillus paracasei', 'additive'), ok('植物乳杆菌', 'Lactobacillus plantarum', 'additive'), ok('干酪乳杆菌', 'Lactobacillus casei', 'additive'), ok('发酵剂', 'starter cultures', 'additive'), ok('树莓浆', 'raspberry puree', 'fruit'), ok('风味发酵乳', 'flavoured fermented milk (yogurt)', 'dairy'),
    ok('乳糖醇', 'lactitol', 'sweetener'), ok('酪蛋白', 'casein', 'dairy'), ok('酪蛋白酸钠', 'sodium caseinate', 'dairy'), ok('酪蛋白酸钙', 'calcium caseinate', 'dairy'),
    ok('酪蛋白磷酸肽', 'casein phosphopeptide', 'dairy'), ok('α-乳白蛋白', 'alpha-lactalbumin', 'dairy'), ok('骨桥蛋白', 'osteopontin (milk)', 'dairy'), ok('乳脂球膜', 'milk fat globule membrane', 'dairy'),
    ok('奶黄', 'custard', 'dairy'), ok('奶茶粉', 'milk tea powder', 'drink'), ok('奶', 'milk', 'dairy'), ok('乳', 'milk', 'dairy'),
    // ---------- eggs
    ok('蛋', 'egg', 'egg'), ok('蛋液', 'liquid egg', 'egg'), ok('全蛋', 'whole egg', 'egg'), ok('全蛋液', 'whole liquid egg', 'egg'), ok('全蛋粉', 'whole egg powder', 'egg'),
    ok('蛋黄', 'egg yolk', 'egg'), ok('蛋黄粉', 'egg yolk powder', 'egg'), ok('蛋黄液', 'liquid egg yolk', 'egg'), ok('蛋清', 'egg white', 'egg'), ok('蛋清粉', 'egg white powder', 'egg'),
    ok('蛋白液', 'liquid egg white', 'egg'), ok('蛋白', 'egg white / protein', 'egg'), ok('蛋白质', 'protein', 'label'), ok('皮蛋', 'century egg', 'egg'), ok('松花蛋', 'century egg', 'egg'),
    ok('咸蛋', 'salted egg', 'egg'), ok('咸蛋黄', 'salted egg yolk', 'egg'), ok('卤蛋', 'braised egg', 'egg'), ok('茶叶蛋', 'tea egg', 'egg'), ok('蛋黄酱', 'mayonnaise', 'condiment'),
    ok('沙拉酱', 'salad dressing', 'condiment'), ok('千岛酱', 'thousand island dressing', 'condiment'), ok('蛋糕', 'cake', 'bakery'), ok('蛋卷', 'egg roll', 'bakery'),
    ok('蛋黄派', 'egg yolk pie', 'bakery'), ok('蛋散', 'egg crisp', 'bakery'), ok('溶菌酶', 'lysozyme (egg)', 'additive'),
    // ---------- proteins and amino acids
    ok('水解植物蛋白', 'hydrolysed vegetable protein', 'additive'), ok('植物水解蛋白', 'hydrolysed vegetable protein', 'additive'), ok('大豆蛋白', 'soy protein', 'plant'),
    ok('大豆分离蛋白', 'soy protein isolate', 'plant'), ok('分离大豆蛋白', 'soy protein isolate', 'plant'), ok('大豆浓缩蛋白', 'soy protein concentrate', 'plant'),
    ok('大豆组织蛋白', 'textured soy protein', 'plant'), ok('小麦蛋白', 'wheat protein', 'grain'), ok('谷朊粉', 'wheat gluten', 'grain'), ok('豌豆蛋白', 'pea protein', 'plant'),
    ok('花生蛋白', 'peanut protein', 'plant'), ok('植物蛋白', 'vegetable protein', 'plant'), ok('赖氨酸', 'lysine', 'additive'), ok('L-赖氨酸', 'L-lysine', 'additive'),
    ok('谷氨酸钠', 'MSG', 'additive'), ok('味精', 'MSG', 'additive'), ok('谷氨酸', 'glutamic acid', 'additive'), ok('天冬氨酸', 'aspartic acid', 'additive'),
    ok('丙氨酸', 'alanine', 'additive'), ok('精氨酸', 'arginine', 'additive'), ok('亮氨酸', 'leucine', 'additive'), ok('异亮氨酸', 'isoleucine', 'additive'),
    ok('缬氨酸', 'valine', 'additive'), ok('苏氨酸', 'threonine', 'additive'), ok('色氨酸', 'tryptophan', 'additive'), ok('苯丙氨酸', 'phenylalanine', 'additive'),
    ok('蛋氨酸', 'methionine', 'additive'), ok('组氨酸', 'histidine', 'additive'), ok('谷氨酰胺', 'glutamine', 'additive'), ok('氨基酸', 'amino acids', 'additive'),
    // ---------- enzymes (fine)
    ok('淀粉酶', 'amylase', 'enzyme'), ok('α-淀粉酶', 'alpha-amylase', 'enzyme'), ok('葡萄糖淀粉酶', 'glucoamylase', 'enzyme'), ok('糖化酶', 'glucoamylase', 'enzyme'),
    ok('木瓜蛋白酶', 'papain', 'enzyme'), ok('菠萝蛋白酶', 'bromelain', 'enzyme'), ok('无花果蛋白酶', 'ficin', 'enzyme'), ok('乳糖酶', 'lactase', 'enzyme'),
    ok('转谷氨酰胺酶', 'transglutaminase (microbial)', 'enzyme'), ok('谷氨酰胺转氨酶', 'transglutaminase', 'enzyme'), ok('TG酶', 'transglutaminase', 'enzyme'),
    ok('纤维素酶', 'cellulase', 'enzyme'), ok('果胶酶', 'pectinase', 'enzyme'), ok('葡萄糖氧化酶', 'glucose oxidase', 'enzyme'), ok('过氧化氢酶', 'catalase', 'enzyme'),
    ok('植酸酶', 'phytase', 'enzyme'), ok('木聚糖酶', 'xylanase', 'enzyme'),
    // ---------- vitamins and minerals
    ok('维生素D3', 'vitamin D3', 'vitamin'), ok('维生素D', 'vitamin D', 'vitamin'), ok('维生素A', 'vitamin A', 'vitamin'), ok('维生素A醋酸酯', 'vitamin A acetate', 'vitamin'),
    ok('维生素E', 'vitamin E', 'vitamin'), ok('dl-α-生育酚', 'dl-alpha-tocopherol', 'vitamin'), ok('生育酚', 'tocopherol', 'vitamin'), ok('混合生育酚', 'mixed tocopherols', 'vitamin'),
    ok('维生素C', 'vitamin C', 'vitamin'), ok('抗坏血酸', 'ascorbic acid', 'vitamin'), ok('L-抗坏血酸', 'L-ascorbic acid', 'vitamin'), ok('抗坏血酸钠', 'sodium ascorbate', 'vitamin'),
    ['抗坏血酸棕榈酸酯', 'caution', 'ascorbyl palmitate (E304; palmitic acid source unverifiable)', 'kàng huài xuè suān zōng lǘ suān zhǐ', 'additive', 'Palmitic acid is normally palm-derived; animal source possible but rare.'], ok('维生素B1', 'vitamin B1', 'vitamin'), ok('维生素B2', 'vitamin B2', 'vitamin'), ok('维生素B6', 'vitamin B6', 'vitamin'),
    ok('维生素B12', 'vitamin B12', 'vitamin'), ok('烟酸', 'niacin', 'vitamin'), ok('烟酰胺', 'niacinamide', 'vitamin'), ok('叶酸', 'folic acid', 'vitamin'), ok('泛酸钙', 'calcium pantothenate', 'vitamin'),
    ok('D-泛酸钙', 'calcium D-pantothenate', 'vitamin'), ok('生物素', 'biotin', 'vitamin'), ok('胆碱', 'choline', 'vitamin'), ok('氯化胆碱', 'choline chloride', 'vitamin'), ok('肌醇', 'inositol', 'vitamin'),
    ok('维生素', 'vitamins', 'vitamin'), ok('核黄素', 'riboflavin', 'vitamin'), ok('硫胺素', 'thiamine', 'vitamin'), ok('碳酸钙', 'calcium carbonate', 'mineral'), ok('磷酸钙', 'calcium phosphate', 'mineral'),
    ok('磷酸三钙', 'tricalcium phosphate', 'mineral'), ok('磷酸氢钙', 'calcium hydrogen phosphate', 'mineral'), ok('磷酸二氢钙', 'monocalcium phosphate', 'mineral'),
    ok('柠檬酸铁铵', 'ferric ammonium citrate', 'mineral'), ok('乳酸亚铁', 'ferrous lactate', 'mineral'), ok('葡萄糖酸亚铁', 'ferrous gluconate', 'mineral'), ok('焦磷酸铁', 'ferric pyrophosphate', 'mineral'),
    ok('硫酸亚铁', 'ferrous sulfate', 'mineral'), ok('氧化锌', 'zinc oxide', 'mineral'), ok('硫酸锌', 'zinc sulfate', 'mineral'), ok('葡萄糖酸锌', 'zinc gluconate', 'mineral'),
    ok('硫酸铜', 'copper sulfate', 'mineral'), ok('亚硒酸钠', 'sodium selenite', 'mineral'), ok('碘酸钾', 'potassium iodate', 'mineral'), ok('碘化钾', 'potassium iodide', 'mineral'),
    ok('氯化钾', 'potassium chloride', 'mineral'), ok('氯化钙', 'calcium chloride', 'mineral'), ok('氯化镁', 'magnesium chloride', 'mineral'), ok('氯化钠', 'sodium chloride', 'mineral'),
    ok('硫酸钙', 'calcium sulfate', 'mineral'), ok('硫酸镁', 'magnesium sulfate', 'mineral'), ok('碳酸镁', 'magnesium carbonate', 'mineral'), ok('葡萄糖酸钙', 'calcium gluconate', 'mineral'),
    ok('葡萄糖酸', 'gluconic acid', 'additive'), ok('葡萄糖酸内酯', 'glucono delta-lactone', 'additive'), ok('亚铁氰化钾', 'potassium ferrocyanide', 'additive'),
    // ---------- acids, preservatives, antioxidants, leavening
    ok('柠檬酸', 'citric acid', 'additive'), ok('柠檬酸钠', 'sodium citrate', 'additive'), ok('柠檬酸钾', 'potassium citrate', 'additive'), ok('柠檬酸钙', 'calcium citrate', 'additive'),
    ok('柠檬酸三乙酯', 'triethyl citrate', 'additive'), ok('苹果酸', 'malic acid', 'additive'), ok('DL-苹果酸', 'DL-malic acid', 'additive'), ok('磷酸', 'phosphoric acid', 'additive'),
    ok('醋酸', 'acetic acid', 'additive'), ok('富马酸', 'fumaric acid', 'additive'), ok('琥珀酸', 'succinic acid', 'additive'), ok('琥珀酸二钠', 'disodium succinate', 'additive'),
    ok('碳酸钠', 'sodium carbonate', 'additive'), ok('碳酸氢钠', 'sodium bicarbonate', 'additive'), ok('小苏打', 'baking soda', 'additive'), ok('碳酸氢铵', 'ammonium bicarbonate', 'additive'),
    ok('碳酸钾', 'potassium carbonate', 'additive'), ok('碳酸氢钾', 'potassium bicarbonate', 'additive'), ok('氢氧化钙', 'calcium hydroxide', 'additive'), ok('氢氧化钠', 'sodium hydroxide', 'additive'),
    ok('焦磷酸钠', 'sodium pyrophosphate', 'additive'), ok('焦磷酸二氢二钠', 'disodium dihydrogen pyrophosphate', 'additive'), ok('三聚磷酸钠', 'sodium tripolyphosphate', 'additive'),
    ok('六偏磷酸钠', 'sodium hexametaphosphate', 'additive'), ok('磷酸二氢钠', 'monosodium phosphate', 'additive'), ok('磷酸氢二钠', 'disodium phosphate', 'additive'),
    ok('磷酸三钠', 'trisodium phosphate', 'additive'), ok('磷酸二氢钾', 'monopotassium phosphate', 'additive'), ok('磷酸氢二钾', 'dipotassium phosphate', 'additive'),
    ok('复合磷酸盐', 'compound phosphates', 'additive'), ok('磷酸盐', 'phosphates', 'additive'), ok('山梨酸钾', 'potassium sorbate', 'additive'), ok('山梨酸', 'sorbic acid', 'additive'),
    ok('苯甲酸钠', 'sodium benzoate', 'additive'), ok('苯甲酸', 'benzoic acid', 'additive'), ok('脱氢乙酸钠', 'sodium dehydroacetate', 'additive'), ok('脱氢乙酸', 'dehydroacetic acid', 'additive'),
    ok('丙酸钙', 'calcium propionate', 'additive'), ok('丙酸钠', 'sodium propionate', 'additive'), ok('双乙酸钠', 'sodium diacetate', 'additive'), ok('纳他霉素', 'natamycin', 'additive'),
    ok('亚硝酸钠', 'sodium nitrite (curing salt)', 'additive'), ok('硝酸钠', 'sodium nitrate', 'additive'), ok('硝酸钾', 'potassium nitrate', 'additive'), ok('亚硫酸钠', 'sodium sulfite', 'additive'),
    ok('焦亚硫酸钠', 'sodium metabisulfite', 'additive'), ok('焦亚硫酸钾', 'potassium metabisulfite', 'additive'), ok('二氧化硫', 'sulfur dioxide', 'additive'),
    ok('对羟基苯甲酸酯', 'parabens', 'additive'), ok('特丁基对苯二酚', 'TBHQ', 'additive'), ok('TBHQ', 'TBHQ', 'additive'), ok('丁基羟基茴香醚', 'BHA', 'additive'), ok('BHA', 'BHA', 'additive'),
    ok('二丁基羟基甲苯', 'BHT', 'additive'), ok('BHT', 'BHT', 'additive'), ok('茶多酚', 'tea polyphenols', 'additive'), ok('迷迭香提取物', 'rosemary extract', 'additive'), ok('植酸', 'phytic acid', 'additive'),
    ok('异抗坏血酸钠', 'sodium erythorbate', 'additive'), ok('D-异抗坏血酸钠', 'sodium D-erythorbate', 'additive'), ok('乙二胺四乙酸二钠', 'disodium EDTA', 'additive'), ok('EDTA', 'EDTA', 'additive'),
    ok('泡打粉', 'baking powder', 'additive'), ok('食用碱', 'alkali (sodium carbonate)', 'additive'), ok('碱水', 'alkaline water (lye)', 'additive'), ok('明矾', 'alum', 'additive'),
    ok('硫酸铝钾', 'potassium alum', 'additive'), ok('硫酸铝铵', 'ammonium alum', 'additive'), ok('二氧化硅', 'silicon dioxide', 'additive'), ok('滑石粉', 'talc', 'additive'),
    ok('硅铝酸钠', 'sodium aluminosilicate', 'additive'), ok('蜂蜡', 'beeswax', 'additive'), ok('巴西棕榈蜡', 'carnauba wax', 'additive'), ok('棕榈蜡', 'carnauba wax', 'additive'),
    ok('白油', 'mineral oil', 'additive'), ok('液体石蜡', 'liquid paraffin', 'additive'), ok('石蜡', 'paraffin', 'additive'), ok('聚二甲基硅氧烷', 'dimethylpolysiloxane', 'additive'),
    ok('二甲基硅油', 'dimethyl silicone oil', 'additive'), ok('丙二醇', 'propylene glycol', 'additive'), ok('聚乙烯吡咯烷酮', 'PVP', 'additive'), ok('薄荷醇', 'menthol', 'additive'),
    ok('麦芽酚', 'maltol', 'additive'), ok('乙酸异戊酯', 'isoamyl acetate', 'additive'), ok('香辛料', 'spices', 'spice'), ok('香料', 'spices / flavouring', 'spice'),
    // ---------- function-class words (anchors for INS codes)
    ok('食品添加剂', 'food additives', 'label'), ok('增稠剂', 'thickener', 'label'), ok('稳定剂', 'stabiliser', 'label'), ok('凝固剂', 'coagulant', 'label'), ok('膨松剂', 'leavening agent', 'label'),
    ok('水分保持剂', 'humectant', 'label'), ok('抗结剂', 'anti-caking agent', 'label'), ok('被膜剂', 'glazing agent', 'label'), ok('消泡剂', 'antifoaming agent', 'label'),
    ok('抗氧化剂', 'antioxidant', 'label'), ok('防腐剂', 'preservative', 'label'), ok('甜味剂', 'sweetener', 'label'), ok('酸度调节剂', 'acidity regulator', 'label'),
    ok('增味剂', 'flavour enhancer', 'label'), ok('护色剂', 'colour retention agent', 'label'), ok('漂白剂', 'bleaching agent', 'label'), ok('面粉处理剂', 'flour treatment agent', 'label'),
    ok('营养强化剂', 'nutrient fortifier', 'label'), ok('着色剂', 'colour', 'label'), ok('色素', 'colour', 'label'), ok('食用色素', 'food colour', 'label'), ok('复配', 'compound (additive)', 'label'),
    ok('复配食品添加剂', 'compound food additive', 'label'), ok('复配增稠剂', 'compound thickener', 'label'), ok('复配乳化剂', 'compound emulsifier', 'label'), ok('复配膨松剂', 'compound leavening agent', 'label'),
    // ---------- colours (fine)
    ok('胭脂红', 'Ponceau 4R (synthetic red, E124)', 'colour', 'Synthetic azo dye — NOT the insect carmine 胭脂虫红.'), ok('胭脂红铝色淀', 'Ponceau 4R aluminium lake', 'colour'),
    ok('焦糖色', 'caramel colour', 'colour'), ok('焦糖', 'caramel', 'colour'), ok('红曲红', 'monascus red', 'colour'), ok('红曲米', 'red yeast rice', 'colour'), ok('红曲粉', 'red yeast rice powder', 'colour'),
    ok('辣椒红', 'paprika red', 'colour'), ok('辣椒油树脂', 'paprika oleoresin', 'colour'), ok('姜黄', 'turmeric', 'colour'), ok('姜黄素', 'curcumin', 'colour'), ok('栀子黄', 'gardenia yellow', 'colour'),
    ok('栀子蓝', 'gardenia blue', 'colour'), ok('叶绿素铜钠盐', 'sodium copper chlorophyllin', 'colour'), ok('叶绿素', 'chlorophyll', 'colour'), ok('二氧化钛', 'titanium dioxide', 'colour'),
    ok('柠檬黄', 'tartrazine', 'colour'), ok('日落黄', 'sunset yellow', 'colour'), ok('亮蓝', 'brilliant blue', 'colour'), ok('诱惑红', 'allura red', 'colour'), ok('赤藓红', 'erythrosine', 'colour'),
    ok('新红', 'new red', 'colour'), ok('靛蓝', 'indigotine', 'colour'), ok('喹啉黄', 'quinoline yellow', 'colour'), ok('酸性红', 'acid red', 'colour'), ok('偶氮玉红', 'azorubine', 'colour'),
    ok('番茄红素', 'lycopene', 'colour'), ok('叶黄素', 'lutein', 'colour'), ok('叶黄素酯', 'lutein esters', 'colour'), ok('β-胡萝卜素', 'beta-carotene', 'colour'), ok('胡萝卜素', 'carotene', 'colour'),
    ok('甜菜红', 'beet red', 'colour'), ok('高粱红', 'sorghum red', 'colour'), ok('葡萄皮红', 'grape skin extract', 'colour'), ok('越橘红', 'bilberry red', 'colour'), ok('黑豆红', 'black bean red', 'colour'),
    ok('黑加仑红', 'blackcurrant red', 'colour'), ok('萝卜红', 'radish red', 'colour'), ok('玫瑰茄红', 'roselle red', 'colour'), ok('可可壳色', 'cocoa shell colour', 'colour'),
    ok('植物炭黑', 'vegetable carbon black', 'colour'), ok('氧化铁红', 'iron oxide red', 'colour'), ok('氧化铁黑', 'iron oxide black', 'colour'), ok('氧化铁', 'iron oxide', 'colour'),
    ok('藻蓝', 'phycocyanin (spirulina blue)', 'colour'), ok('螺旋藻蓝', 'spirulina blue', 'colour'), ok('花青素', 'anthocyanin', 'colour'), ok('紫甘薯色素', 'purple sweet potato colour', 'colour'),
    ok('紫玉米色素', 'purple corn colour', 'colour'), ok('虾青素', 'astaxanthin (algae or yeast)', 'colour'),
    // ---------- sweeteners and sugars
    ok('阿斯巴甜', 'aspartame', 'sweetener'), ok('安赛蜜', 'acesulfame K', 'sweetener'), ok('三氯蔗糖', 'sucralose', 'sweetener'), ok('糖精钠', 'sodium saccharin', 'sweetener'),
    ok('甜蜜素', 'cyclamate', 'sweetener'), ok('环己基氨基磺酸钠', 'sodium cyclamate', 'sweetener'), ok('纽甜', 'neotame', 'sweetener'), ok('爱德万甜', 'advantame', 'sweetener'),
    ok('甜菊糖苷', 'steviol glycosides', 'sweetener'), ok('甜菊糖', 'stevia', 'sweetener'), ok('罗汉果甜苷', 'mogroside', 'sweetener'), ok('罗汉果提取物', 'monk fruit extract', 'sweetener'),
    ok('索马甜', 'thaumatin', 'sweetener'), ok('木糖醇', 'xylitol', 'sweetener'), ok('麦芽糖醇', 'maltitol', 'sweetener'), ok('麦芽糖醇液', 'maltitol syrup', 'sweetener'),
    ok('山梨糖醇', 'sorbitol', 'sweetener'), ok('山梨糖醇液', 'sorbitol syrup', 'sweetener'), ok('赤藓糖醇', 'erythritol', 'sweetener'), ok('甘露糖醇', 'mannitol', 'sweetener'),
    ok('异麦芽酮糖醇', 'isomalt', 'sweetener'), ok('异麦芽酮糖', 'isomaltulose', 'sweetener'), ok('异麦芽糖醇', 'isomalt', 'sweetener'), ok('阿洛酮糖', 'allulose', 'sweetener'),
    ok('塔格糖', 'tagatose', 'sweetener'), ok('低聚果糖', 'fructo-oligosaccharides', 'sweetener'), ok('低聚异麦芽糖', 'isomalto-oligosaccharides', 'sweetener'),
    ok('低聚半乳糖', 'galacto-oligosaccharides', 'sweetener'), ok('低聚木糖', 'xylo-oligosaccharides', 'sweetener'), ok('低聚糖', 'oligosaccharides', 'sweetener'), ok('菊粉', 'inulin', 'fibre'),
    ok('聚葡萄糖', 'polydextrose', 'fibre'), ok('抗性糊精', 'resistant dextrin', 'fibre'), ok('水溶性膳食纤维', 'soluble dietary fibre', 'fibre'), ok('膳食纤维', 'dietary fibre', 'fibre'),
    ok('麦芽糊精', 'maltodextrin', 'sugar'), ok('糊精', 'dextrin', 'sugar'), ok('环状糊精', 'cyclodextrin', 'sugar'), ok('β-环状糊精', 'beta-cyclodextrin', 'sugar'),
    ok('麦芽糖浆', 'maltose syrup', 'sugar'), ok('麦芽糖', 'maltose', 'sugar'), ok('麦芽', 'malt', 'grain'), ok('麦芽粉', 'malt powder', 'grain'), ok('麦芽提取物', 'malt extract', 'grain'),
    ok('葡萄糖浆', 'glucose syrup', 'sugar'), ok('葡萄糖', 'glucose', 'sugar'), ok('果葡糖浆', 'high-fructose syrup', 'sugar'), ok('高果糖浆', 'high-fructose corn syrup', 'sugar'),
    ok('果糖', 'fructose', 'sugar'), ok('结晶果糖', 'crystalline fructose', 'sugar'), ok('蔗糖', 'sucrose', 'sugar'), ok('白砂糖', 'white sugar', 'sugar'), ok('绵白糖', 'soft white sugar', 'sugar'),
    ok('冰糖', 'rock sugar', 'sugar'), ok('红糖', 'brown sugar', 'sugar'), ok('黑糖', 'dark brown sugar', 'sugar'), ok('赤砂糖', 'raw brown sugar', 'sugar'), ok('黄糖', 'yellow sugar', 'sugar'),
    ok('原糖', 'raw sugar', 'sugar'), ok('糖粉', 'icing sugar', 'sugar'), ok('转化糖浆', 'invert syrup', 'sugar'), ok('转化糖', 'invert sugar', 'sugar'), ok('蜂蜜', 'honey', 'sugar'),
    ok('枫糖浆', 'maple syrup', 'sugar'), ok('糖蜜', 'molasses', 'sugar'), ok('海藻糖', 'trehalose', 'sugar'), ok('淀粉糖', 'starch sugar', 'sugar'), ok('玉米糖浆', 'corn syrup', 'sugar'),
    ok('大米糖浆', 'rice syrup', 'sugar'), ok('糖浆', 'syrup', 'sugar'), ok('糖', 'sugar', 'sugar'), ok('代糖', 'sugar substitute', 'sweetener'),
    // ---------- starches and grains
    ok('淀粉', 'starch', 'grain'), ok('玉米淀粉', 'corn starch', 'grain'), ok('木薯淀粉', 'tapioca starch', 'grain'), ok('马铃薯淀粉', 'potato starch', 'grain'), ok('土豆淀粉', 'potato starch', 'grain'),
    ok('红薯淀粉', 'sweet potato starch', 'grain'), ok('小麦淀粉', 'wheat starch', 'grain'), ok('绿豆淀粉', 'mung bean starch', 'grain'), ok('变性淀粉', 'modified starch', 'grain'),
    ok('改性淀粉', 'modified starch', 'grain'), ok('羟丙基二淀粉磷酸酯', 'hydroxypropyl distarch phosphate', 'grain'), ok('乙酰化二淀粉磷酸酯', 'acetylated distarch phosphate', 'grain'),
    ok('醋酸酯淀粉', 'starch acetate', 'grain'), ok('氧化淀粉', 'oxidised starch', 'grain'), ok('预糊化淀粉', 'pregelatinised starch', 'grain'), ok('淀粉磷酸酯钠', 'sodium starch phosphate', 'grain'),
    ok('辛烯基琥珀酸淀粉钠', 'starch sodium octenyl succinate', 'grain'), ok('糯米粉', 'glutinous rice flour', 'grain'), ok('粘米粉', 'rice flour', 'grain'), ok('大米粉', 'rice flour', 'grain'),
    ok('米粉', 'rice noodles / rice flour', 'grain'), ok('小麦粉', 'wheat flour', 'grain'), ok('面粉', 'flour', 'grain'), ok('高筋小麦粉', 'strong wheat flour', 'grain'), ok('低筋小麦粉', 'cake flour', 'grain'),
    ok('全麦粉', 'wholemeal flour', 'grain'), ok('麦麸', 'wheat bran', 'grain'), ok('燕麦', 'oats', 'grain'), ok('燕麦片', 'rolled oats', 'grain'), ok('燕麦粉', 'oat flour', 'grain'),
    ok('大麦', 'barley', 'grain'), ok('大麦粉', 'barley flour', 'grain'), ok('荞麦', 'buckwheat', 'grain'), ok('荞麦粉', 'buckwheat flour', 'grain'), ok('玉米', 'corn', 'grain'),
    ok('玉米粉', 'corn flour', 'grain'), ok('玉米片', 'corn flakes', 'grain'), ok('高粱', 'sorghum', 'grain'), ok('小米', 'millet', 'grain'), ok('黄米', 'glutinous millet', 'grain'),
    ok('黑米', 'black rice', 'grain'), ok('糯米', 'glutinous rice', 'grain'), ok('紫米', 'purple rice', 'grain'), ok('大米', 'rice', 'grain'), ok('香米', 'fragrant rice', 'grain'),
    ok('糙米', 'brown rice', 'grain'), ok('薏米', 'coix seed', 'grain'), ok('薏仁', 'coix seed', 'grain'), ok('藜麦', 'quinoa', 'grain'), ok('芡实', 'fox nut', 'plant'),
    ok('莲子', 'lotus seed', 'plant'), ok('山药', 'Chinese yam', 'vegetable'), ok('芋头', 'taro', 'vegetable'), ok('红薯', 'sweet potato', 'vegetable'), ok('紫薯', 'purple sweet potato', 'vegetable'),
    ok('马铃薯', 'potato', 'vegetable'), ok('土豆', 'potato', 'vegetable'), ok('薯片', 'potato chips', 'snack'), ok('木薯', 'cassava', 'vegetable'), ok('魔芋', 'konjac', 'vegetable'),
    ok('魔芋粉', 'konjac flour', 'vegetable'), ok('葛根', 'kudzu root', 'plant'), ok('葛根粉', 'kudzu starch', 'plant'), ok('藕粉', 'lotus root starch', 'plant'), ok('莲藕', 'lotus root', 'vegetable'),
    ok('面条', 'noodles', 'grain'), ok('面', 'noodles / flour', 'grain'), ok('面饼', 'noodle cake', 'grain'), ok('挂面', 'dried noodles', 'grain'), ok('粉丝', 'glass noodles', 'grain'),
    ok('粉条', 'starch noodles', 'grain'), ok('河粉', 'flat rice noodles', 'grain'), ok('年糕', 'rice cake', 'grain'), ok('饼干', 'biscuit', 'bakery'), ok('面包', 'bread', 'bakery'),
    ok('面包屑', 'bread crumbs', 'bakery'), ok('膨化', 'puffed', 'label'),
    // ---------- beans, nuts, seeds
    ok('大豆', 'soybean', 'bean'), ok('黄豆', 'soybean', 'bean'), ok('黑豆', 'black soybean', 'bean'), ok('绿豆', 'mung bean', 'bean'), ok('红豆', 'red bean', 'bean'),
    ok('赤小豆', 'adzuki bean', 'bean'), ok('红小豆', 'adzuki bean', 'bean'), ok('芸豆', 'kidney bean', 'bean'), ok('腰豆', 'kidney bean', 'bean'), ok('鹰嘴豆', 'chickpea', 'bean'),
    ok('蚕豆', 'broad bean', 'bean'), ok('豌豆', 'pea', 'bean'), ok('青豌豆', 'green peas', 'bean'), ok('添加量', 'amount added', 'label'), ok('辐照', 'irradiated', 'label'), ok('辐照处理', 'irradiation treated', 'label'), ok('青豆', 'green pea / soybean', 'bean'), ok('毛豆', 'edamame', 'bean'), ok('扁豆', 'lentil / hyacinth bean', 'bean'),
    ok('豆浆', 'soy milk', 'bean'), ok('豆粉', 'soy flour', 'bean'), ok('豆奶', 'soy milk', 'bean'), ok('豆腐', 'tofu', 'bean'), ok('豆干', 'dried tofu', 'bean'), ok('豆皮', 'tofu skin', 'bean'),
    ok('腐竹', 'dried tofu sticks', 'bean'), ok('豆腐皮', 'tofu skin', 'bean'), ok('千张', 'thin tofu sheets', 'bean'), ok('豆腐干', 'dried tofu', 'bean'), ok('豆渣', 'soy pulp', 'bean'),
    ok('纳豆', 'natto', 'bean'), ok('豆豉', 'fermented black beans', 'condiment'), ok('豆瓣', 'broad-bean paste', 'condiment'), ok('豆瓣酱', 'doubanjiang (bean paste)', 'condiment'),
    ok('黄豆酱', 'soybean paste', 'condiment'), ok('大豆酱', 'soybean paste', 'condiment'), ok('甜面酱', 'sweet bean sauce', 'condiment'), ok('面酱', 'wheat paste', 'condiment'),
    ok('豆沙', 'sweet bean paste', 'filling'), ok('红豆沙', 'red bean paste', 'filling'), ok('绿豆沙', 'mung bean paste', 'filling'), ok('豆沙馅', 'bean paste filling', 'filling'),
    ok('莲蓉', 'lotus seed paste', 'filling'), ok('莲蓉馅', 'lotus paste filling', 'filling'), ok('枣泥', 'date paste', 'filling'), ok('五仁', 'five-nut filling', 'filling'),
    ok('芝麻', 'sesame', 'seed'), ok('黑芝麻', 'black sesame', 'seed'), ok('白芝麻', 'white sesame', 'seed'), ok('芝麻酱', 'sesame paste', 'condiment'), ok('芝麻糊', 'sesame paste dessert', 'seed'),
    ok('花生', 'peanut', 'nut'), ok('花生酱', 'peanut butter', 'condiment'), ok('花生碎', 'crushed peanuts', 'nut'), ok('花生仁', 'peanut kernels', 'nut'), ok('核桃', 'walnut', 'nut'),
    ok('核桃仁', 'walnut kernels', 'nut'), ok('杏仁', 'almond', 'nut'), ok('巴旦木', 'almond', 'nut'), ok('扁桃仁', 'almond', 'nut'), ok('腰果', 'cashew', 'nut'), ok('开心果', 'pistachio', 'nut'),
    ok('榛子', 'hazelnut', 'nut'), ok('松子', 'pine nut', 'nut'), ok('松仁', 'pine nut', 'nut'), ok('夏威夷果', 'macadamia', 'nut'), ok('碧根果', 'pecan', 'nut'), ok('山核桃', 'hickory nut', 'nut'),
    ok('板栗', 'chestnut', 'nut'), ok('栗子', 'chestnut', 'nut'), ok('葵花籽', 'sunflower seed', 'seed'), ok('瓜子', 'melon / sunflower seeds', 'seed'), ok('南瓜籽', 'pumpkin seed', 'seed'),
    ok('南瓜子', 'pumpkin seed', 'seed'), ok('西瓜籽', 'watermelon seed', 'seed'), ok('西瓜子', 'watermelon seed', 'seed'), ok('亚麻籽', 'flaxseed', 'seed'), ok('奇亚籽', 'chia seed', 'seed'),
    ok('火麻仁', 'hemp seed', 'seed'), ok('坚果', 'nuts', 'nut'),
    // ---------- fruits
    ok('桂圆', 'longan', 'fruit'), ok('龙眼', 'longan', 'fruit'), ok('红枣', 'red date', 'fruit'), ok('大枣', 'jujube', 'fruit'), ok('枸杞', 'goji berry', 'fruit'), ok('葡萄干', 'raisin', 'fruit'),
    ok('蔓越莓', 'cranberry', 'fruit'), ok('蔓越莓干', 'dried cranberry', 'fruit'), ok('蓝莓', 'blueberry', 'fruit'), ok('草莓', 'strawberry', 'fruit'), ok('芒果', 'mango', 'fruit'),
    ok('芒果干', 'dried mango', 'fruit'), ok('菠萝', 'pineapple', 'fruit'), ok('凤梨', 'pineapple', 'fruit'), ok('椰子', 'coconut', 'fruit'), ok('椰浆', 'coconut cream', 'fruit'),
    ok('椰奶', 'coconut milk', 'fruit'), ok('椰蓉', 'desiccated coconut', 'fruit'), ok('椰丝', 'coconut shreds', 'fruit'), ok('椰子粉', 'coconut powder', 'fruit'), ok('椰果', 'nata de coco', 'fruit'),
    ok('椰子水', 'coconut water', 'fruit'), ok('香蕉', 'banana', 'fruit'), ok('苹果', 'apple', 'fruit'), ok('梨', 'pear', 'fruit'), ok('桃', 'peach', 'fruit'), ok('水蜜桃', 'honey peach', 'fruit'),
    ok('黄桃', 'yellow peach', 'fruit'), ok('杏', 'apricot', 'fruit'), ok('李子', 'plum', 'fruit'), ok('西梅', 'prune', 'fruit'), ok('梅子', 'plum', 'fruit'), ok('话梅', 'preserved plum', 'fruit'),
    ok('乌梅', 'smoked plum', 'fruit'), ok('青梅', 'green plum', 'fruit'), ok('山楂', 'hawthorn', 'fruit'), ok('柠檬', 'lemon', 'fruit'), ok('青柠', 'lime', 'fruit'), ok('橙', 'orange', 'fruit'),
    ok('橙子', 'orange', 'fruit'), ok('橘子', 'mandarin', 'fruit'), ok('柚子', 'pomelo', 'fruit'), ok('西柚', 'grapefruit', 'fruit'), ok('葡萄', 'grape', 'fruit'), ok('樱桃', 'cherry', 'fruit'),
    ok('车厘子', 'cherry', 'fruit'), ok('荔枝', 'lychee', 'fruit'), ok('哈密瓜', 'hami melon', 'fruit'), ok('西瓜', 'watermelon', 'fruit'), ok('木瓜', 'papaya', 'fruit'), ok('番石榴', 'guava', 'fruit'),
    ok('百香果', 'passion fruit', 'fruit'), ok('火龙果', 'dragon fruit', 'fruit'), ok('猕猴桃', 'kiwi', 'fruit'), ok('奇异果', 'kiwi', 'fruit'), ok('石榴', 'pomegranate', 'fruit'), ok('柿子', 'persimmon', 'fruit'),
    ok('无花果', 'fig', 'fruit'), ok('榴莲', 'durian', 'fruit'), ok('山竹', 'mangosteen', 'fruit'), ok('杨梅', 'bayberry', 'fruit'), ok('杨桃', 'starfruit', 'fruit'), ok('枇杷', 'loquat', 'fruit'),
    ok('桑葚', 'mulberry', 'fruit'), ok('黑加仑', 'blackcurrant', 'fruit'), ok('树莓', 'raspberry', 'fruit'), ok('覆盆子', 'raspberry', 'fruit'), ok('黑莓', 'blackberry', 'fruit'), ok('沙棘', 'sea buckthorn', 'fruit'),
    ok('刺梨', 'chestnut rose', 'fruit'), ok('果汁', 'fruit juice', 'fruit'), ok('浓缩果汁', 'concentrated juice', 'fruit'), ok('果酱', 'jam', 'fruit'), ok('果粒', 'fruit pieces', 'fruit'),
    ok('果泥', 'fruit puree', 'fruit'), ok('果干', 'dried fruit', 'fruit'), ok('水果', 'fruit', 'fruit'), ok('果', 'fruit', 'fruit'),
    // ---------- vegetables, fungi, seaweed
    ok('番茄', 'tomato', 'vegetable'), ok('西红柿', 'tomato', 'vegetable'), ok('番茄酱', 'tomato paste / ketchup', 'condiment'), ok('番茄沙司', 'ketchup', 'condiment'), ok('番茄粉', 'tomato powder', 'vegetable'),
    ok('洋葱', 'onion', 'vegetable'), ok('葱', 'scallion', 'vegetable'), ok('大葱', 'leek / scallion', 'vegetable'), ok('小葱', 'chives', 'vegetable'), ok('香葱', 'chives', 'vegetable'),
    ok('青葱', 'spring onion', 'vegetable'), ok('蒜', 'garlic', 'vegetable'), ok('大蒜', 'garlic', 'vegetable'), ok('蒜粉', 'garlic powder', 'spice'), ok('蒜末', 'minced garlic', 'vegetable'),
    ok('姜', 'ginger', 'spice'), ok('生姜', 'ginger', 'spice'), ok('姜粉', 'ginger powder', 'spice'), ok('老姜', 'mature ginger', 'spice'), ok('辣椒', 'chilli', 'spice'), ok('干辣椒', 'dried chilli', 'spice'),
    ok('辣椒粉', 'chilli powder', 'spice'), ok('辣椒面', 'chilli flakes', 'spice'), ok('辣椒酱', 'chilli sauce', 'condiment'), ok('辣椒油', 'chilli oil', 'condiment'), ok('红油', 'chilli oil', 'condiment'),
    ok('青椒', 'green pepper', 'vegetable'), ok('甜椒', 'bell pepper', 'vegetable'), ok('花椒', 'Sichuan pepper', 'spice'), ok('青花椒', 'green Sichuan pepper', 'spice'), ok('麻椒', 'Sichuan pepper', 'spice'),
    ok('藤椒', 'rattan pepper', 'spice'), ok('胡椒', 'pepper', 'spice'), ok('白胡椒', 'white pepper', 'spice'), ok('黑胡椒', 'black pepper', 'spice'), ok('胡椒粉', 'ground pepper', 'spice'),
    ok('八角', 'star anise', 'spice'), ok('大料', 'star anise', 'spice'), ok('桂皮', 'cassia bark', 'spice'), ok('香叶', 'bay leaf', 'spice'), ok('月桂叶', 'bay leaf', 'spice'), ok('小茴香', 'fennel seed', 'spice'),
    ok('茴香', 'fennel', 'spice'), ok('孜然', 'cumin', 'spice'), ok('孜然粉', 'cumin powder', 'spice'), ok('丁香', 'clove', 'spice'), ok('豆蔻', 'cardamom', 'spice'), ok('白豆蔻', 'white cardamom', 'spice'),
    ok('草果', 'tsaoko (black cardamom)', 'spice'), ok('砂仁', 'amomum (cardamom)', 'spice'), ok('白芷', 'angelica root', 'spice'), ok('甘草', 'liquorice', 'spice'), ok('陈皮', 'dried tangerine peel', 'spice'),
    ok('山奈', 'sand ginger', 'spice'), ok('沙姜', 'sand ginger', 'spice'), ok('良姜', 'galangal', 'spice'), ok('高良姜', 'galangal', 'spice'), ok('香茅', 'lemongrass', 'spice'),
    ok('柠檬草', 'lemongrass', 'spice'), ok('咖喱', 'curry', 'spice'), ok('咖喱粉', 'curry powder', 'spice'), ok('芥末', 'mustard / wasabi', 'spice'), ok('芥末粉', 'mustard powder', 'spice'),
    ok('辣根', 'horseradish', 'spice'), ok('山葵', 'wasabi', 'spice'), ok('芫荽', 'coriander', 'herb'), ok('香菜', 'coriander', 'herb'), ok('芹菜', 'celery', 'vegetable'), ok('西芹', 'celery', 'vegetable'),
    ok('胡萝卜', 'carrot', 'vegetable'), ok('白萝卜', 'white radish', 'vegetable'), ok('萝卜', 'radish', 'vegetable'), ok('卷心菜', 'cabbage', 'vegetable'), ok('包菜', 'cabbage', 'vegetable'),
    ok('甘蓝', 'cabbage / kale', 'vegetable'), ok('西兰花', 'broccoli', 'vegetable'), ok('花菜', 'cauliflower', 'vegetable'), ok('菠菜', 'spinach', 'vegetable'), ok('生菜', 'lettuce', 'vegetable'),
    ok('白菜', 'Chinese cabbage', 'vegetable'), ok('小白菜', 'bok choy', 'vegetable'), ok('青菜', 'green vegetables', 'vegetable'), ok('油菜', 'rapeseed greens', 'vegetable'), ok('菜心', 'choy sum', 'vegetable'),
    ok('芥菜', 'mustard greens', 'vegetable'), ok('梅干菜', 'preserved mustard greens', 'vegetable'), ok('梅菜', 'preserved mustard greens', 'vegetable'), ok('雪菜', 'pickled potherb mustard', 'vegetable'),
    ok('酸菜', 'pickled cabbage', 'vegetable'), ok('泡菜', 'pickles / kimchi', 'vegetable'), ok('榨菜', 'pickled mustard tuber', 'vegetable'), ok('萝卜干', 'dried radish', 'vegetable'),
    ok('酸笋', 'pickled bamboo shoot', 'vegetable'), ok('笋', 'bamboo shoot', 'vegetable'), ok('竹笋', 'bamboo shoot', 'vegetable'), ok('笋干', 'dried bamboo shoot', 'vegetable'),
    ok('木耳', 'wood ear fungus', 'fungus'), ok('黑木耳', 'black fungus', 'fungus'), ok('银耳', 'snow fungus', 'fungus'), ok('香菇', 'shiitake', 'fungus'), ok('香菇粉', 'shiitake powder', 'fungus'),
    ok('蘑菇', 'mushroom', 'fungus'), ok('蘑菇精', 'mushroom seasoning', 'additive'), ok('蔬之鲜', 'vegetable seasoning', 'additive'), ok('平菇', 'oyster mushroom', 'fungus'),
    ok('金针菇', 'enoki', 'fungus'), ok('杏鲍菇', 'king oyster mushroom', 'fungus'), ok('口蘑', 'button mushroom', 'fungus'), ok('牛肝菌', 'porcini (bolete) mushroom', 'fungus'),
    ok('松茸', 'matsutake', 'fungus'), ok('松露', 'truffle', 'fungus'), ok('竹荪', 'bamboo fungus', 'fungus'), ok('猴头菇', 'lion\'s mane mushroom', 'fungus'), ok('茶树菇', 'tea tree mushroom', 'fungus'),
    ok('海鲜菇', 'seafood mushroom (shimeji)', 'fungus'), ok('黄花菜', 'dried lily flower', 'vegetable'), ok('海带', 'kelp', 'seaweed'), ok('海带丝', 'shredded kelp', 'seaweed'), ok('紫菜', 'laver', 'seaweed'),
    ok('海苔', 'seaweed snack', 'seaweed'), ok('裙带菜', 'wakame', 'seaweed'), ok('海藻', 'seaweed', 'seaweed'), ok('螺旋藻', 'spirulina', 'seaweed'), ok('小球藻', 'chlorella', 'seaweed'),
    ok('石花菜', 'agar seaweed', 'seaweed'), ok('琼脂', 'agar', 'thickener'), ok('海盐', 'sea salt', 'salt'), ok('豆芽', 'bean sprouts', 'vegetable'), ok('黄瓜', 'cucumber', 'vegetable'),
    ok('南瓜', 'pumpkin', 'vegetable'), ok('冬瓜', 'winter melon', 'vegetable'), ok('丝瓜', 'luffa', 'vegetable'), ok('苦瓜', 'bitter melon', 'vegetable'), ok('茄子', 'aubergine', 'vegetable'),
    ok('玉米笋', 'baby corn', 'vegetable'), ok('荸荠', 'water chestnut', 'vegetable'), ok('马蹄', 'water chestnut', 'vegetable'), ok('菱角', 'water caltrop', 'vegetable'), ok('秋葵', 'okra', 'vegetable'),
    ok('芦笋', 'asparagus', 'vegetable'), ok('韭菜', 'Chinese chives', 'vegetable'), ok('蒜苗', 'garlic sprouts', 'vegetable'), ok('青蒜', 'green garlic', 'vegetable'), ok('豌豆苗', 'pea shoots', 'vegetable'),
    ok('蕨菜', 'fiddlehead fern', 'vegetable'), ok('荠菜', 'shepherd\'s purse', 'vegetable'), ok('蔬菜', 'vegetables', 'vegetable'), ok('脱水蔬菜', 'dehydrated vegetables', 'vegetable'), ok('菜包', 'vegetable sachet', 'misc'),
    // ---------- tea, coffee, drinks, herbs
    ok('茶', 'tea', 'drink'), ok('绿茶', 'green tea', 'drink'), ok('红茶', 'black tea', 'drink'), ok('乌龙茶', 'oolong tea', 'drink'), ok('普洱茶', 'pu-erh tea', 'drink'), ok('茉莉花茶', 'jasmine tea', 'drink'),
    ok('茶叶', 'tea leaves', 'drink'), ok('茶粉', 'tea powder', 'drink'), ok('抹茶', 'matcha', 'drink'), ok('咖啡', 'coffee', 'drink'), ok('咖啡粉', 'coffee powder', 'drink'), ok('速溶咖啡', 'instant coffee', 'drink'),
    ok('咖啡因', 'caffeine', 'additive'), ok('巧克力', 'chocolate', 'sweet'), ok('黑巧克力', 'dark chocolate', 'sweet'), ok('白巧克力', 'white chocolate', 'sweet'), ok('巧克力酱', 'chocolate spread', 'sweet'),
    ok('可乐', 'cola', 'drink'), ok('碳酸水', 'carbonated water', 'drink'), ok('苏打水', 'soda water', 'drink'), ok('气泡水', 'sparkling water', 'drink'), ok('纯净水', 'purified water', 'drink'),
    ok('饮用水', 'drinking water', 'drink'), ok('矿泉水', 'mineral water', 'drink'), ok('天然矿泉水', 'natural mineral water', 'drink'), ok('水', 'water', 'drink'), ok('二氧化碳', 'carbon dioxide', 'additive'),
    ok('氮气', 'nitrogen', 'additive'), ok('菊花', 'chrysanthemum', 'herb'), ok('金银花', 'honeysuckle', 'herb'), ok('罗汉果', 'monk fruit', 'herb'), ok('桂花', 'osmanthus', 'herb'), ok('玫瑰', 'rose', 'herb'),
    ok('玫瑰花', 'rose petals', 'herb'), ok('薰衣草', 'lavender', 'herb'), ok('薄荷', 'mint', 'herb'), ok('薄荷脑', 'menthol', 'additive'), ok('薄荷油', 'peppermint oil', 'additive'), ok('人参', 'ginseng', 'herb'),
    ok('西洋参', 'American ginseng', 'herb'), ok('黄芪', 'astragalus', 'herb'), ok('当归', 'angelica sinensis', 'herb'), ok('党参', 'codonopsis', 'herb'), ok('枸杞子', 'goji berry', 'herb'),
    ok('决明子', 'cassia seed', 'herb'), ok('茯苓', 'poria', 'herb'), ok('百合', 'lily bulb', 'herb'), ok('黑枸杞', 'black goji', 'herb'), ok('石斛', 'dendrobium', 'herb'), ok('灵芝', 'reishi', 'fungus'),
    ok('蛹虫草', 'cordyceps militaris (fungus)', 'fungus'), ok('蜂王浆', 'royal jelly', 'bee'), ok('蜂胶', 'propolis', 'bee'), ok('蜂花粉', 'bee pollen', 'bee'), ok('蜂巢', 'honeycomb', 'bee'),
    ok('红曲', 'red yeast rice', 'additive'), ok('酸梅', 'sour plum', 'fruit'), ok('紫苏', 'perilla', 'herb'), ok('罂粟籽', 'poppy seed', 'seed'), ok('大麻籽', 'hemp seed', 'seed'),
    // ---------- salt and basics
    ok('食用盐', 'salt', 'salt'), ok('食盐', 'salt', 'salt'), ok('盐', 'salt', 'salt'), ok('精制盐', 'refined salt', 'salt'), ok('加碘盐', 'iodised salt', 'salt'), ok('岩盐', 'rock salt', 'salt'),
    ok('低钠盐', 'low-sodium salt', 'salt'), ok('竹盐', 'bamboo salt', 'salt'), ok('湖盐', 'lake salt', 'salt'), ok('井盐', 'well salt', 'salt'),
    // ---------- fish (fine)
    ok('鱼', 'fish', 'seafood'), ok('鱼浆', 'fish paste', 'seafood'), ok('鱼板', 'kamaboko (fish cake)', 'seafood'), ok('鱼糕', 'fish cake', 'seafood'), ok('鱼饼', 'fish cake', 'seafood'),
    ok('鱼卷', 'fish roll', 'seafood'), ok('鱼粉', 'fish powder', 'seafood'), ok('鱼子', 'fish roe', 'seafood'), ok('鱼籽', 'fish roe', 'seafood'), ok('鱼子酱', 'caviar', 'seafood'),
    ok('鱼松', 'fish floss', 'seafood'), ok('鱼肉松', 'fish floss', 'seafood'), ok('鱼皮', 'fish skin', 'seafood'), ok('鱼唇', 'fish lips', 'seafood'), ok('鱼肚', 'fish maw', 'seafood'),
    ok('鱼鳔', 'fish maw', 'seafood'), ok('鱼露', 'fish sauce', 'condiment'), ok('鱼干', 'dried fish', 'seafood'), ok('鱼片', 'fish fillet', 'seafood'), ok('鱼柳', 'fish fillet', 'seafood'),
    ok('鱼排', 'fish fillet', 'seafood'), ok('鱼翅', 'shark fin', 'seafood'), ok('鱼香', 'yuxiang flavour (no fish)', 'label'), ok('三文鱼', 'salmon', 'seafood'), ok('鲑鱼', 'salmon', 'seafood'),
    ok('金枪鱼', 'tuna', 'seafood'), ok('吞拿鱼', 'tuna', 'seafood'), ok('鳕鱼', 'cod', 'seafood'), ok('鲈鱼', 'perch / bass', 'seafood'), ok('鲤鱼', 'carp', 'seafood'), ok('草鱼', 'grass carp', 'seafood'),
    ok('鲫鱼', 'crucian carp', 'seafood'), ok('鲢鱼', 'silver carp', 'seafood'), ok('带鱼', 'ribbonfish', 'seafood'), ok('黄鱼', 'yellow croaker', 'seafood'), ok('鲅鱼', 'Spanish mackerel', 'seafood'),
    ok('秋刀鱼', 'saury', 'seafood'), ok('沙丁鱼', 'sardine', 'seafood'), ok('凤尾鱼', 'anchovy', 'seafood'), ok('鳀鱼', 'anchovy', 'seafood'), ok('银鱼', 'whitebait', 'seafood'),
    ok('鳗鱼', 'eel', 'seafood'), ok('鳝鱼', 'swamp eel', 'seafood'), ok('黄鳝', 'swamp eel', 'seafood'), ok('泥鳅', 'loach', 'seafood'), ok('鲶鱼', 'catfish', 'seafood'), ok('鲇鱼', 'catfish', 'seafood'),
    ok('罗非鱼', 'tilapia', 'seafood'), ok('多春鱼', 'shishamo smelt', 'seafood'), ok('鲨鱼', 'shark', 'seafood'), ok('海鱼', 'sea fish', 'seafood'), ok('鱼类', 'fish', 'seafood'),
    ok('蟹味菇', 'crab-flavour mushroom (shimeji)', 'fungus'), ok('鲣鱼', 'bonito (fish)', 'seafood'), ok('鲣鱼粉', 'bonito powder', 'seafood'), ok('木鱼花', 'bonito flakes (katsuobushi)', 'seafood'),
    ok('混合坚果', 'mixed nuts', 'nut'), ok('每日坚果', 'daily nut mix', 'nut'),
    // ---------- snacks and misc fine
    ok('凉粉', 'starch jelly', 'grain'), ok('凉皮', 'cold starch noodles', 'grain'), ok('魔芋爽', 'konjac snack', 'snack'), ok('果冻', 'jelly', 'sweet', 'Check separately for 明胶; most Chinese jellies use carrageenan or konjac.'),
    ok('布丁', 'pudding', 'sweet', 'Check separately for 明胶.'), ok('棉花糖', 'marshmallow', 'sweet', 'Usually contains 明胶 — check.'), ok('软糖', 'gummy candy', 'sweet', 'Often contains 明胶 — check.'),
    ok('QQ糖', 'gummy candy', 'sweet', 'Usually contains 明胶 — check.'), ok('口香糖', 'chewing gum', 'sweet'), ok('糖果', 'candy', 'sweet'), ok('薯条', 'fries', 'snack'), ok('锅巴', 'rice crisps', 'snack'),
    ok('米饼', 'rice cracker', 'snack'), ok('雪饼', 'rice cracker', 'snack'), ok('仙贝', 'senbei rice cracker', 'snack'), ok('爆米花', 'popcorn', 'snack'), ok('蜜饯', 'candied fruit', 'sweet'), ok('果脯', 'preserved fruit', 'sweet'), ok('山楂片', 'hawthorn flakes', 'sweet'), ok('凤梨酥', 'pineapple cake', 'bakery'), ok('曲奇', 'cookie', 'bakery'),
    ok('威化', 'wafer', 'bakery'), ok('蛋白糖', 'meringue', 'sweet'), ok('夹心', 'filling', 'label'), ok('馅料', 'filling', 'label'), ok('涂层', 'coating', 'label'), ok('包衣', 'coating', 'label'),
    ok('油条', 'fried dough stick', 'bakery'), ok('麻花', 'fried dough twist', 'bakery'), ok('凉茶', 'herbal tea', 'drink'), ok('王老吉', 'Wong Lo Kat herbal tea', 'drink'),
    ok('食品', 'food', 'label'), ok('食用', 'edible', 'label'), ok('精炼', 'refined', 'label'), ok('浓缩', 'concentrated', 'label'), ok('脱水', 'dehydrated', 'label'), ok('冻干', 'freeze-dried', 'label'),
    ok('烘焙', 'baked', 'label'), ok('油炸', 'fried', 'label'), ok('非油炸', 'non-fried', 'label'), ok('烤', 'roasted', 'label'), ok('熏', 'smoked', 'label'), ok('腌', 'pickled / cured', 'label'),
    ok('含量', 'content', 'label'), ok('添加', 'added', 'label'), ok('不添加', 'no added', 'label'), ok('无添加', 'no additives', 'label'), ok('零添加', 'zero additives', 'label'),
    ok('天然', 'natural', 'label'), ok('有机', 'organic', 'label'), ok('以上', 'or more', 'label'), ok('以下', 'or less', 'label'), ok('等', 'etc.', 'label'), ok('和', 'and', 'label'),
    ok('及', 'and', 'label'), ok('或', 'or', 'label'), ok('提取物', 'extract', 'label'), ok('浸膏', 'extract', 'label'), ok('粉', 'powder', 'label'), ok('片', 'slices', 'label'), ok('干', 'dried', 'label'),
    ok('丁', 'diced', 'label'), ok('末', 'minced', 'label'), ok('汁', 'juice', 'label'), ok('酱', 'sauce / paste', 'condiment'), ok('油', 'oil', 'oil'), ok('水解', 'hydrolysed', 'label'),
    ok('复合', 'compound', 'label'), ok('混合', 'mixed', 'label'), ok('调制', 'blended', 'label'), ok('速溶', 'instant', 'label'), ok('即食', 'ready to eat', 'label'), ok('真空', 'vacuum', 'label'),
    ok('充氮', 'nitrogen-flushed', 'label'), ok('防潮', 'moisture-proof', 'label'), ok('干燥剂', 'desiccant', 'label', 'Not for eating.'), ok('脱氧剂', 'oxygen absorber', 'label', 'Not for eating.')
  );
})(HALAL_DB);
