/* HalalCheck knowledge base — part 4: judgement by PRODUCT TYPE for packets without an ingredient list
 * (独立小包装 single-serve packets split from a bulk bag, showroom snacks, loose sweets).
 * Shape: [name(s) as on the pack, level, english, typical ingredients, what decides halal status]
 * level: haram | likely | doubtful | meat | caution | clean   (same meaning as the verdict levels)
 * The judgement is by TYPE, not by the actual list — the app says so and asks for the big pack when possible.
 */
(function (DB) {
  DB.products = [
    // ---------- seeds, nuts, beans, dried fruit: fine
    ['瓜子|葵花籽|葵瓜子|南瓜子|西瓜子', 'clean', 'roasted seeds', 'seeds, salt, sometimes spices, sweetener, flavouring', 'Plant product; flavoured versions add 香精 (minor).'],
    ['花生|香酥花生|鱼皮花生|怪味花生|酒鬼花生', 'clean', 'peanuts (coated or roasted)', 'peanuts, oil, flour coating, salt, spices, flavouring', '酒鬼 is a brand name, no alcohol. Fine.'],
    ['青豌豆|豌豆|蒜香豌豆|香辣豌豆', 'clean', 'roasted green peas', 'peas, vegetable oil, seasoning, flavouring', 'Fine; seasoning packs are plant-based.'],
    ['蚕豆|兰花豆|怪味豆', 'clean', 'roasted broad beans', 'broad beans, oil, salt, spices', 'Fine.'],
    ['坚果|混合坚果|每日坚果|腰果|巴旦木|核桃|碧根果|夏威夷果|开心果|榛子|松子', 'clean', 'nuts', 'nuts, sometimes dried fruit, oil, salt, honey coating', 'Fine.'],
    ['果干|蜜饯|话梅|西梅|杏干|芒果干|葡萄干|蔓越莓干|山楂片|山楂条|山楂卷', 'clean', 'dried / candied fruit', 'fruit, sugar, salt, sweeteners, citric acid', 'Fine; some 话梅 use liquorice and sweeteners (fine).'],
    ['红枣|枣夹核桃|桂圆|枸杞', 'clean', 'dates, longan, goji', 'fruit, nuts', 'Fine.'],
    ['海带丝|海带结|海苔|紫菜|裙带菜', 'clean', 'seaweed snack', 'seaweed, oil, salt, spices', 'Fine; some seaweed snacks add 鱼露 or 虾粉 (fish fine, shrimp = seafood).'],
    ['魔芋爽|魔芋丝|魔芋', 'clean', 'konjac snack', 'konjac, water, oil, chilli, spices, flavouring', 'Fine.'],
    ['辣条|面筋|大面筋|亲嘴烧|卫龙', 'clean', 'spicy gluten strips', 'wheat flour, oil, salt, sugar, chilli, spices, additives, flavouring', 'Plant product; "meat" names on latiao are only flavour descriptors.'],
    ['豆干|豆腐干|香干|卤豆干|素鸡', 'clean', 'dried tofu snack', 'soybeans, oil, soy sauce, spices', 'Fine unless the pack lists 料酒 (cooking wine).'],
    ['薯片|薯条|乐事|可比克|上好佳', 'caution', 'potato chips', 'potato, oil, salt, flavour powder', 'Meat-flavour varieties (烤肉味, 牛肉味, 鸡汁味) can contain real meat powder — check the flavour name; plain and vegetable flavours are fine.'],
    ['虾条|虾片|龙虾片', 'clean', 'prawn crackers', 'starch, shrimp powder, oil, salt', 'Shrimp content: fine for Shafi\'i, Maliki, Hanbali; Hanafi caution.'],
    ['锅巴|米饼|雪饼|仙贝|旺旺', 'clean', 'rice crackers', 'rice, oil, sugar, salt, soy sauce, flavouring', 'Fine.'],
    ['饼干|苏打饼干|夹心饼干|威化|曲奇|奥利奥|趣多多', 'caution', 'biscuits / cookies / wafers', 'flour, sugar, vegetable fat or butter, emulsifiers (E471 class), flavouring', 'Usually fine; emulsifier fat source unverifiable; some cookies use 猪油 (lard) — rare in branded packs.'],
    ['蛋卷|凤凰卷|鸡蛋卷', 'caution', 'egg rolls', 'flour, egg, sugar, butter or lard', 'Traditional recipes use lard; branded ones mostly butter or vegetable fat — look for 猪油 on the big pack.'],
    ['蛋黄酥|老婆饼|苏式月饼|鲜肉月饼|桃酥|杏仁酥|绿豆糕|云片糕|牛舌饼|酥饼', 'likely', 'Chinese flaky pastries', 'flour, sugar, lard (猪油) or shortening, fillings', 'Traditional pastry made with lard; 鲜肉月饼 is pork-filled. Treat as non-halal unless the big pack shows 植物油 only or 清真.'],
    ['月饼|广式月饼', 'caution', 'mooncake', 'flour, syrup, oil, lotus or bean paste, egg yolk', 'Cantonese mooncakes are usually vegetable oil; 五仁 may contain 火腿 (ham); 鲜肉/云腿 varieties are pork. Check the big pack.'],
    ['沙琪玛|萨其马', 'caution', 'sachima (fried dough cake)', 'flour, egg, sugar, oil', 'Traditionally fried in lard; modern branded packs use vegetable oil.'],
    ['麻花|油条|馓子', 'caution', 'fried dough twists', 'flour, oil, sugar, salt', 'Fine when fried in vegetable oil; small makers may use lard.'],
    ['面包|吐司|蛋糕|蒸蛋糕|小蛋糕|瑞士卷|铜锣烧|蛋黄派|派', 'caution', 'bread / cake', 'flour, sugar, egg, fat, emulsifiers, flavouring, sometimes gelatin in fillings', 'Usually fine; cream fillings may use gelatin — check 明胶 on the big pack.'],
    ['肉松饼|肉松小贝|肉松面包|肉松蛋糕', 'likely', 'meat-floss pastry', 'flour, sugar, fat, meat floss (pork unless stated)', 'Pork floss unless the pack says 鸡肉松 or 牛肉松 with 清真.'],
    ['猪肉脯|猪肉干|猪肉松|靖江肉脯', 'haram', 'pork jerky / floss', 'pork, sugar, soy sauce, spices', 'Pork.'],
    ['肉脯|肉干|肉松|肉粒|肉丸', 'likely', 'meat snack (species not stated)', 'meat, sugar, soy sauce, spices', 'Unspecified meat in China normally means pork.'],
    ['牛肉干|牛肉粒|牛肉条|手撕牛肉|风干牛肉|牛肉丸', 'meat', 'beef jerky / beef snack', 'beef, salt, sugar, soy sauce, spices, sometimes 料酒', 'Halal only if 清真-slaughtered (Inner Mongolia / Xinjiang 清真 brands exist); marinades may contain cooking wine.'],
    ['鸭脖|鸭翅|鸭掌|鸭舌|鸭锁骨|鸭肠|鸭胗|周黑鸭|绝味|鸭肉', 'meat', 'braised duck parts', 'duck, salt, sugar, spices, soy sauce, often 料酒 (cooking wine)', 'Duck is halal only if slaughtered Islamically; the brine usually contains cooking wine.'],
    ['鸡爪|泡椒凤爪|虎皮凤爪|鸡翅|鸡腿|鸡脖|鸡胸肉|鸡肉', 'meat', 'chicken parts', 'chicken, salt, vinegar, chilli, spices, sometimes 料酒', 'Halal only if slaughtered Islamically; 泡椒凤爪 brines often include cooking wine.'],
    ['火腿肠|香肠|烤肠|腊肠|午餐肉|培根', 'likely', 'sausage / ham', 'pork and chicken, starch, salt, nitrite', 'Pork unless stated 鸡肉 or 牛肉 with 清真.'],
    ['鱼豆腐|鱼板|鱼丸|蟹棒|鱼糕|鱼肉', 'caution', 'fish paste snack', 'fish surimi, starch, oil, flavouring', 'Fish is fine; some brands add pork fat or chicken — check the big pack.'],
    ['鱼皮|鱼干|小鱼仔|小鱼干|鳗鱼|鱿鱼丝|鱿鱼', 'clean', 'dried fish / squid', 'fish or squid, salt, sugar, spices', 'Fish fine; squid is seafood (Hanafi caution).'],
    ['卤蛋|茶叶蛋|鹌鹑蛋|乡巴佬', 'clean', 'braised eggs', 'egg, water, salt, soy sauce, spices', 'Fine unless 料酒 is listed.'],
    ['豆腐|千张|腐竹', 'clean', 'tofu products', 'soybeans, water, coagulant', 'Fine.'],
    ['果冻|布丁|蒟蒻|喜之郎', 'caution', 'jelly / pudding', 'water, sugar, carrageenan or konjac, flavouring, sometimes gelatin', 'Most Chinese jellies use carrageenan (fine); milk puddings and imported jellies may use gelatin.'],
    ['软糖|QQ糖|橡皮糖|棉花糖|牛轧糖|奶糖|大白兔|太妃糖|焦糖|夹心糖', 'likely', 'gummy / nougat / milk candy', 'sugar, syrup, gelatin (明胶), milk powder, flavouring', 'Gummies, nougat, marshmallow and most milk candies (incl. 大白兔) contain gelatin — pig skin in China unless 清真.'],
    ['硬糖|水果糖|薄荷糖|棒棒糖|酥糖|芝麻糖|花生糖|麦芽糖|龙须糖|冰糖', 'clean', 'hard / boiled / sesame / peanut candy', 'sugar, syrup, flavouring, colour', 'Fine; check 胭脂虫红 (carmine) on red sweets if strict.'],
    ['巧克力|德芙|费列罗|士力架|脆香米|M&M', 'caution', 'chocolate', 'sugar, cocoa, milk powder, emulsifiers (E322, E476), flavouring', 'Usually fine; liqueur chocolates (酒心) are not; some bars contain gelatin or E471-class emulsifiers.'],
    ['口香糖|泡泡糖|木糖醇', 'clean', 'chewing gum', 'gum base, sweeteners, flavouring', 'Fine (gum base may contain stearates, minor).'],
    ['奶片|奶酪棒|奶酪|芝士', 'caution', 'milk tablets / cheese sticks', 'milk powder, sugar, cheese (rennet unknown), gelatin in some', 'Cheese rennet and gelatin are the questions.'],
    ['酸奶|乳酸菌饮料|养乐多|安慕希|纯甄|莫斯利安', 'caution', 'yogurt / cultured drink', 'milk, sugar, cultures, thickener (pectin, agar or gelatin)', 'Fine when the thickener is pectin/agar; many ambient yogurts list 明胶 (gelatin).'],
    ['牛奶|纯牛奶|鲜牛奶|巴氏奶|旺仔牛奶|豆奶|豆浆|杏仁露|椰汁|椰子水|核桃露|凉茶|王老吉|加多宝|可乐|雪碧|果汁|茶饮料|矿泉水|纯净水|苏打水|气泡水|咖啡', 'clean', 'drinks', 'water, milk or plant base, sugar, flavouring, emulsifiers in nut milks', 'Fine. Anything with 酒 in the name (米酒, 果酒, 奶啤) is alcoholic.'],
    ['奶茶|蜜雪冰城|喜茶|奈雪', 'clean', 'milk tea', 'tea, milk or creamer, sugar, tapioca pearls', 'Fine; toppings like 布丁 may use gelatin.'],
    ['方便面|泡面|康师傅|统一|螺蛳粉|酸辣粉|米线|自热火锅|自热米饭', 'caution', 'instant noodles / self-heating meals', 'noodles plus seasoning sachets: often 牛油, 鸡精, 猪骨粉, 猪油 or 肉', 'Flavour name decides: 红烧牛肉 (beef, slaughter?), 香辣排骨 and 猪骨 (pork), 老坛酸菜 usually fine, 自热火锅 usually beef tallow. Needs the sachet lists.'],
    ['火锅底料|海底捞|麻辣烫', 'caution', 'hotpot base', 'beef tallow or vegetable oil, chilli, spices, 鸡精, sometimes lard', '清真 hotpot bases exist (e.g. labelled 清真 from Inner Mongolia); others use non-halal tallow or lard.'],
    ['饺子|包子|馄饨|小笼包|烧卖|汤圆|粽子|春卷|锅贴', 'likely', 'dumplings / buns / filled rice snacks', 'flour, fillings (pork unless stated), sometimes lard in sweet fillings', 'Fillings are pork unless the name says 牛肉, 羊肉, 鸡肉 or 素 (vegetarian).'],
    ['年糕|糍粑|青团|艾草青团|麻薯|雪媚娘|大福', 'caution', 'glutinous rice cakes', 'glutinous rice, sugar, bean paste, sometimes lard or gelatin', 'Plain ones fine; 青团 fillings (蛋黄肉松) often contain pork floss; 雪媚娘 creams may use gelatin.'],
    ['米酒|醪糟|甜酒|黄酒|啤酒|白酒|葡萄酒|果酒|奶啤|RIO|鸡尾酒', 'haram', 'alcoholic drink', 'fermented rice, grapes or grain; ethanol', 'Alcoholic.'],
    ['酒心巧克力|酒酿|酒鬼|醉', 'doubtful', 'liquor-related name', 'may contain liquor or lees', '酒心 = liqueur-filled (haram); 酒鬼 is only a brand; 醉X dishes are liquor-marinated (haram).'],
    ['饮用水|纯净水', 'clean', 'water', 'water', 'Fine.'],
    ['龟苓膏|仙草|烧仙草|凉粉', 'caution', 'herbal jelly', 'herbs, starch, sugar; traditional 龟苓膏 contains turtle shell', '仙草/凉粉 are plant jellies (fine); 龟苓膏 only if no 龟板 (turtle) is listed.'],
    ['燕窝|阿胶|阿胶糕', 'doubtful', 'tonic products', '燕窝 = bird\'s nest (fine); 阿胶 = donkey-hide gelatin (haram)', '阿胶 products are donkey-derived: avoid.'],
    ['蛋白棒|能量棒|代餐|蛋白粉', 'caution', 'protein / meal-replacement', 'whey or soy protein, syrup, gelatin in some bars, emulsifiers', 'Whey and gelatin are the questions.'],
    ['冰淇淋|雪糕|冰棍|冰激凌', 'caution', 'ice cream', 'milk, sugar, cream, emulsifiers, stabilisers (sometimes gelatin), flavouring', 'Most use plant stabilisers; some use gelatin or alcohol flavours (rum-raisin).'],
    ['蛋糕卷|提拉米苏|黑森林', 'caution', 'cream cakes', 'flour, egg, cream, sometimes gelatin, sometimes liqueur', '提拉米苏 and 黑森林 traditionally contain liqueur.'],
    ['肉夹馍|煎饼|手抓饼|葱油饼|烧饼|锅盔', 'caution', 'savoury flatbreads', 'flour, oil (sometimes lard), fillings', '肉夹馍 fillings are pork unless 牛肉; 葱油饼 small makers may use lard.'],
    ['炸鸡|鸡排|汉堡|热狗', 'meat', 'fried chicken / burgers', 'chicken or beef, breading, oil', 'Halal only from 清真 outlets; 热狗 sausages usually pork.'],
    ['鸡精|鸡粉|味精|鸡汁', 'meat', 'bouillon seasoning', 'salt, MSG, chicken fat or powder', '鸡精 usually contains chicken fat — slaughter unverified; 味精 (MSG) is fine.'],
    ['酱油|生抽|老抽|醋|陈醋|蚝油|豆瓣酱|甜面酱|辣椒酱|老干妈|芝麻酱|花生酱|番茄酱|沙拉酱|蛋黄酱', 'caution', 'condiments', 'soybeans, wheat, salt; oyster extract in 蚝油; some sauces list 料酒 or 食用酒精; 老干妈 has 肉末 varieties', 'Soy sauce and vinegar are fine; check 蚝油 (oyster), 料酒/酒精, and meat varieties of 老干妈 (牛肉末 or 肉末).'],
  ];
})(HALAL_DB);
